build.sbt
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala

Fix data type mapping from catalog to spark. This is the first of a series of PRs to support more data types, such as varchar and decimal.
Notable differences in catalog types and Spark types:
|CatalogDataType|SparkDataType|
|-|-|
|bigint|long|
|int|integer|
|smallint|short|
|tinyint|byte|
Now these and struct type can be mapped correctly (as well as all other types)

Fix catalog-to-spark data type mapping

---

README.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintVersion.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala

Re-publishing previous closed PR https://github.com/opensearch-project/opensearch-spark/pull/11
Previously the Flint version info is hardcoding. Added a new class to manage the version and use it across the codebase. Updated README with version and compatibility matrix accordingly: https://github.com/dai-chen/opensearch-spark/blob/add-flint-version-and-doc/README.md#prerequisites
N/A

Add version and update doc

---

flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala

1. Fixed failed test on new added version in Flint metadata
2. Changed UT to assert on partial metadata JSON to minimize maintenance efforts
N/A

Fix test failure on Flint version in metadata

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala

1. Add covering index implementation to `FlintSpark` API
2. Extract `FlintSparkIndexBuilder` and `FlintSparkSuite` with common code from skipping and covering index
1. Generate unique ID column for Flint sink Idempotency
2. Support filtering condition for partial indexing
3. Update user manual after SQL support ready
4. https://github.com/opensearch-project/opensearch-spark/issues/24
Manual test example as below and will move to user manual doc once SQL support is ready:
```
$ spark-shell \
--jars /xxx/flint-spark-integration-assembly-0.1.0-SNAPSHOT.jar \
--conf spark.sql.extensions=org.opensearch.flint.spark.FlintSparkExtensions  \
--conf spark.datasource.flint.host=xxx.us-east-1.es.amazonaws.com  \
--conf spark.datasource.flint.port=-1  \
--conf spark.datasource.flint.scheme=https \ …
```

Add covering index in Flint Spark API

---

docs/index.md
flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSqlSkippingIndexAstBuilder.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala

1. Added SQL support for `CREATE/DROP/REFRESH` statement for covering index.
2. Updated user manual: https://github.com/dai-chen/opensearch-spark/blob/add-covering-index-sql-support/docs/index.md#covering-index
3. Refactor Flint SQL AST builder to separate and mix-in AST builder for different derived dataset
Will publish PR for `SHOW/DESC` statement separately for review convenience.
Create covering index with auto refresh enabled and drop it when not needed:
```
spark-sql> CREATE INDEX orderkey_and_quantity 
... ON stream.lineitem_tiny (l_orderkey, l_quantity)
... WITH (auto_refresh = true);
spark-sql> DROP INDEX orderkey_and_quantity ON stream.lineitem_tiny;
```
OpenSearch index looks like:
```
GET flint_stream_lineitem_tiny_orderkey_and_quantity_index/_mapping
{ …
```

Add create, drop and refresh covering index SQL support

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/function/TumbleFunction.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/function/TumbleFunctionSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkWindowingFunctionITSuite.scala

Add `TUMBLE` windowing function which is required by materialized view support.
The function generates a new column called `window`. It's a struct field consist of `start` and `end` field inside. The implementation is actually delegated to Spark existing `window()` function. Here is an example:
```
spark-sql>
... SELECT window, COUNT(*)
... FROM stream.lineitem_tiny
... GROUP BY TUMBLE(l_shipdate, '1 week')
... ORDER BY window.start
... LIMIT 10;
window	count(1)
{"start":1992-01-02 00:00:00,"end":1992-01-09 00:00:00}	1390
{"start":1992-06-04 00:00:00,"end":1992-06-11 00:00:00}	24980
{"start":1992-07-09 00:00:00,"end":1992-07-16 00:00:00}	24964
{"start":1992-07-16 00:00:00,"end":1992-07-23 00:00:00}	24957
{"start":1992-07-30 00:00:00,"end":1992-08-06 00:00:00}	25012
{"start":1992-08-06 …
```

Add tumble windowing function

---

build.sbt
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala

Close scroll context properly and add IT.
n/a

Bug Fix, close scroll context

---

spark-sql-application/src/main/java/org/opensearch/sql/FlintDelegatingSessionCatalog.java
spark-sql-application/src/test/scala/org/opensearch/sql/FlintDelegatingSessionCatalogTest.scala

In Spark. spark_catalog default catalog name. With FlintDelegatingSessionCatalog, User could customize
catalog name, the implementation delegate to V2SessionCatalog in current SparkSession.
```
Usage
Add configuration
--conf spark.sql.catalog.mycatalog = org.opensearch.sql.FlintDelegatingSessionCatalog
Run query
USE mycatalog;
SHOW catalogs;
> mycatalog
```

Add FlintDelegatingSessionCatalog

---

spark-sql-application/src/main/java/org/opensearch/sql/FlintDelegatingSessionCatalog.java
spark-sql-application/src/test/scala/org/opensearch/sql/FlintDelegatingSessionCatalogTest.scala

Add more test for FlintDelegatingSessionCatalog
n/a

Add more test for FlintDelegatingSessionCatalog

---

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala

1. Add basic auth support when connect to OpenSearch. flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
2. Local Test passed.
https://github.com/opensearch-project/opensearch-spark/issues/46

add basic auth

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala

Persist env info in Flint metadata, such as EMR-S job info. We persist them for CREATE statement regardless of index options, such as `auto_refresh`.
1. Refactor Flint metadata to de-dup serialization code in https://github.com/opensearch-project/opensearch-spark/issues/24
2. Remove hardcoding env name in https://github.com/opensearch-project/opensearch-spark/issues/59
For EMR-S Spark:
```
CREATE SKIPPING INDEX ON myglue.default.http_logs (clientip VALUE_SET);
GET flint_myglue_default_http_logs_skipping_index/_mapping
{
"mappings": {
"_meta": {
"kind": "skipping",
"indexedColumns": 
...
"source": "myglue.default.http_logs",
"version": "0.1.0",
"properties": {
"env": {
"SERVERLESS_EMR_VIRTUAL_CLUSTER_ID": "XXXXXX",
"SERVERLESS_EMR_JOB_ID": "YYYYYY"
}
}
},
...
CREATE INDEX …
```

Persisting runtime env info into Flint metadata

---

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintMetadata.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala

1. Add new `index_settings` option. Please see doc: https://github.com/dai-chen/opensearch-spark/blob/add-index-settings-option/docs/index.md#create-index-options
2. Use a new `FlintMetadata.indexSettings` field to pass it to Flint client. Will refactor the Flint metadata and finalize spec in https://github.com/opensearch-project/opensearch-spark/issues/24
```
spark-sql> CREATE INDEX orderkey_and_quantity
> ON stream.lineitem_tiny (l_orderkey, l_quantity)
> WITH (
>   index_settings = '{"number_of_shards":9,"number_of_replicas":2}'
> );
GET flint_stream_lineitem_tiny_orderkey_and_quantity_index/_settings
{
"flint_stream_lineitem_tiny_orderkey_and_quantity_index": {
"settings": {
"index": {
"creation_date": "1695680614547",
"number_of_shards": "9",
"number_of_replicas": "2",
"uuid": …
```

Add index settings option in create statement

---

.github/workflows/test-and-build-workflow.yml
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlParser.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/SparkSqlAstBuilder.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/opensearch/sql/SQLJob.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
spark-sql-application/src/test/scala/org/opensearch/sql/SQLJobTest.scala

reformat code using `sbt scalafmtAll`

---

docs/index.md
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexOptionsSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala

1. Added validation for option name provided in WITH clause and throw exception for invalid/unknown name
2. For clarity, Store option with default value in Flint metadata even if unspecified in SQL.
https://github.com/opensearch-project/opensearch-spark/issues/65

Add validation for index options

---

.github/workflows/test-and-build-workflow.yml
flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala

In `flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java`, we encountered a conversion problem when transforming the index mapping to `FlintMetadata`. The root cause can be traced back to changes made in [this PR](https://github.com/opensearch-project/opensearch-spark/pull/70/files#diff-c3bdd10ec081d200e375aa601acff4c39b10bb4c34862634f56859f0054fedbf).
Previously, `FlintMetadata` stored its content as a simple string. However, the recent changes have made its structure more complex, introducing fields like `version`, `name`, `kind`, `source`, `indexedColumns`, `options`, `properties`, `schema`, and `indexSettings`.
Given that Flint index is specialized for storing covering index and materialized view metadata, it's not a typical data index. To address …

Fix FlintMetadata conversion issue in FlintOpenSearchClient

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/package.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedViewSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala

1. Add materialized view implementation in Flint Spark API layer
2. Refactor index `build()` API with a new `buildStream()` API. See details below.
3. Extract remaining deserialize logic to new `FlintSparkIndexFactory`.
Will publish separate PR for issues below:
1. Fix issue that windowing function, tumble() or built-in window(), cannot be used in manual/batch refresh job
2. Add more index options for incremental refreshing: watermark_delay, output mode and generic JSON map for any params we can pass to DataStreamWriter.options directly.
3. Need to handle issues with large backlog
a. control initial micro batch size (config `maxFilesPerTrigger` seems unlimited by default?)
b. process oldest data first to avoid data dropped due to watermark
4. If we can support JOIN query in future [TBD]
| …

Add materialized view in Flint Spark API

---

build.sbt
flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchUpdater.java
flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintCommand.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/VerificationResult.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/DefaultShutdownHookManager.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/RealTimeProvider.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/ShutdownHookManagerTrait.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/TimeProvider.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/JobMatchers.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/MockTimeProvider.scala
spark-sql-application/src/test/scala/org/opensearch/sql/SQLJobTest.scala

- **Read (R)**: Source queries from the OpenSearch flint-query-submission index.
- **Execute (E)**: Run queries within the SparkContext environment.
- **Publish (P)**:
- Push results to the flint-query-result index.
- Update query state in the flint-query-submission index.
- **Loop (L)**: Continue process until a set exit condition is reached.
Additional improvements:
- Enable cancelation of running statements in Spark.
- Fail statements that wait too long.
- Provide detailed error feedback.
- Introduce query run time metric.
Testing:
- Introduced unit tests.
- Conducted manual tests.
https://github.com/opensearch-project/opensearch-spark/issues/79
https://github.com/opensearch-project/opensearch-spark/issues/80
https://github.com/opensearch-project/opensearch-spark/issues/83 …

Implement REPL mode in Spark and enhance error handling

---

docs/index.md
flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala

Add missing `REFRESH` statement for materialized view. Earlier I met some problem in IT. So I didn't include refresh statement in previous PR and just found I missed it. Fixed IT issue and add this missing statement.
https://github.com/opensearch-project/opensearch-spark/issues/25

Add missing refresh materialized view statement

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala

Spark `StructType.fromDDL()` requires all columns quoted if any special character. Previously all table/index/column names after Flint parser has been unquoted. Quote them before calling fromDDL method and finally it is unquoted in OpenSearch doc as before.
```
CREATE MATERIALIZED VIEW test
AS
SELECT startTime AS `start.time`
...
start.time string not null,count long not null
----^^^
at org.apache.spark.sql.catalyst.parser.ParseException.withCommand(ParseDriver.scala:306)
at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parse(ParseDriver.scala:143)
at org.apache.spark.sql.catalyst.parser.AbstractSqlParser.parseTableSchema(ParseDriver.scala:76)
at org.apache.spark.sql.types.StructType$.fromDDL(StructType.scala:543)
at org.opensearch.flint.spark.FlintSparkIndex$.generateSchemaJSON(F …
```

Fix column name with special character when create materialized view

---

docs/index.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala

Add new Flint config for checkpoint mandatory option. It is enabled by default which means all incremental refresh (`CREATE` statement with `auto_refresh=true`) must provide `checkpoint_location`. Doc: https://github.com/dai-chen/opensearch-spark/blob/add-mandatory-checkpoint-option/docs/index.md#configurations
Currently all Spark streaming job related validation happens when job start. For example, OS index is created even though job start failed due to missing checkpoint location. For this checkpoint validation, it can be solved by building streaming job early. However, other check on table/options maybe performed only when job start. Need to figure out how to validate early in general. Issue: https://github.com/opensearch-project/opensearch-spark/issues/65
```
spark-sql> CREATE …
```

Add checkpoint mandatory option

---

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java

1. enforce wait_for for all write operation.
2. fix bug when close timeout scroll. https://github.com/opensearch-project/OpenSearch/issues/11121
1. https://github.com/opensearch-project/opensearch-spark/issues/132

Bug fix, handle close scroll exception

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala

Revert previous changes https://github.com/opensearch-project/opensearch-spark/pull/125/files#diff-3ba13ed226c6bfc748e11ae7c79ad2b47783ab2a16805dfdd142818fa9796c70 because PPL plugin still assumes these 2 fields present when deserialization.
Without it, drop statement will throw syntax exception:
```
$ curl localhost:9200/_plugins/_async_query -X POST -H "Content-Type: application/json" -d'
{
"datasource" : "glue_1",
"lang" : "sql",
"query" : "DROP INDEX chen_all_columns ON mys3.default.http_logs"
}'
{
"status": 400,
"error": {
"type": "IllegalArgumentException",
"reason": "Invalid Request",
"details": "Provided Index doesn\u0027t exist"
}
}
```
Mock EMR env variable and create skipping index:
<pre>
$ <b>export SERVERLESS_EMR_VIRTUAL_CLUSTER_ID=test_app</b>
$ <b>export …

Revert EMR info in Flint metadata

---

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchReader.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala

if scroll context timeout, return empty response.
#146

Bug Fix, handle scroll timeout exception

---

flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintCommand.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/app/FlintInstanceTest.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/CommandContext.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/CommandState.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/DefaultThreadPoolFactory.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/ThreadPoolFactory.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/util/MockThreadPoolFactory.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/util/MockTimeProvider.scala

Features:
- Add mutual exclusivity in session-based emr-s jobs to ensure only one job runs at a time, enhancing system stability during blue/green deployments. This allows active job exclusion and seamless task pickup by new jobs. Details in #94.
Fixes:
- Resolve a bug where long-running queries failed to cancel post-index mapping verification, by introducing timely query cancellation checks within the REPL loop.
- Address issue #138 with the proposed short-term fix, improving reliability.
Tests:
- Conducted manual testing to validate blue/green deployment support and query cancellation.
- Extended unit tests to cover new features and bug fixes.
https://github.com/opensearch-project/opensearch-spark/issues/138
https://github.com/opensearch-project/opensearch-spark/issues/94
By submitting …

Implement blue/green deployment support in REPL mode

---

flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/app/FlintInstanceTest.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala

- Added handling for scenarios where jobStartTime is not present in the JSON input.
- Ensures FlintInstance deserialization remains robust and error-free even when jobStartTime is missing.
Testing:
1. Extended unit tests to cover the new case.
2. Conducted manual sanity tests to ensure stability and correctness.
https://github.com/opensearch-project/opensearch-spark/issues/152

Handle Missing jobStartTime in JSON Deserialization

---

flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/app/FlintInstanceTest.scala

This commit changes the serialization format of the 'excludeJobIds' field in the session document. Previously serialized as an array (e.g., ["id1", "id2"]), this field is now formatted as a comma-separated string ("id1,id2"). This adjustment is made to ensure compatibility with plugins that currently do not support array parsing. This simplification aids in seamless integration and easier data handling in downstream processes.
Testing done:
* modified unit test
Signed-off-by: Kaituo Li <kaituo@amazon.com>
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main …

Refactor 'excludeJobIds' Serialization for Spark Job Compatibility

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala

This commit specifically tackles the issue detailed in opensearch-project/opensearch-spark#116. Previously, regardless of whether a streaming job was successfully initiated or encountered syntax/semantic errors during creation, the main thread would indefinitely wait for the streaming job's termination. This behavior often led to situations where the main thread would hang indefinitely, waiting for a streaming job that had not even started due to errors.
This update introduces a change: spark.streams.awaitAnyTermination() is now invoked only if the streaming query is executed without encountering any exceptions.
Testing Performed:
* Replicated the original issue to confirm its presence.
* Applied the fix and verified that the issue of indefinite waiting has been successfully resolved. …

Resolve Forever Waiting Issue in FlintJob for Streaming Jobs

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/package.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala

1. Avoid throwing exception which will cause all subsequent task executions cancelled
2. Follow REPL heartbeat updater to use Spark daemon thread pool
N/A

Improve Flint index monitor error handling

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

- Added detailed logging to improve visibility during streaming job cleanup.
- Decreased REPL job inactivity timeout from 30 to 10 minutes..
Tested manually to ensure new logs are correctly displayed during streaming job cleanup.
https://github.com/opensearch-project/opensearch-spark/issues/157

Enhance Logging for Job Cleanup and Reduce REPL Inactivity Timeout

---

flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/app/FlintInstanceTest.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

This commit introduces two key improvements:
1. An initial delay is added to start the heartbeat mechanism, reducing the risk of concurrent update conflicts.
2. The 'jobId' in the session store is updated at the beginning to properly manage and evict old jobs for the same session.
Testing Performed:
1. Manual sanity testing was conducted.
2. It was ensured that old jobs eventually exit after a new job for the same session starts.
3. The functionality of the heartbeat mechanism was verified to still work effectively.
https://github.com/opensearch-project/opensearch-spark/issues/162
https://github.com/opensearch-project/opensearch-spark/issues/159
https://github.com/opensearch-project/opensearch-spark/issues/145
By submitting this pull request, I confirm that my contribution is made under …

Enhance Session Job Handling and Heartbeat Mechanism

---

flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogEntry.scala
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchUpdater.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala

* In **Flint.createIndex**, create ***query_execution_request*** index if not exist 
* Check ***query_execution_request,*** before write to ***query_execution_request* **index, if index not exist, throw IllegalStateException, emit metrics **QueryExecutionRequestIndexNotFound**.
* When write
* In translog state update, ***query_execution_request* **index, service not available / write block, throw IllegalStateException. Emit metrics **QueryExecutionRequestIndexWriteFail** 
* heartbeat update, ***query_execution_request* **index, service not available / write block, catch exception, Emit metrics **QueryExecutionRequestIndexWriteFail.** After 5 times, Monitor system detect the job lastUpdateTime is stale. if index is green, Monitor system retry EMR-S job. if index is RED / write block. …

Request index not exist handling

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala

* Add sleep 2 seconds between write result index and update state.
* choose 2 seconds because by default index refresh interval is 1s. add 1s as buffer.
* sleep 2s does not impact current query latency.
* sleep 2s increase query latency of query in waiting state. we does not expect much query in the queue, we accept this risk for now.
* It is a migration plan, it does fix the bug.
* Test with script and spark, 50 times, not issue found.
More detail in https://github.com/opensearch-project/opensearch-spark/issues/171
https://github.com/opensearch-project/opensearch-spark/issues/171
For more information on following Developer Certificate of Origin and signing off your commits, …

Migrate resutIndex and requestIndex state inconsistency issue

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/ThreadPoolFactory.scala

Resolve an issue where a non-daemon thread, potentially created by a bug in dependencies, prevents the driver from shutting down properly. The fix ensures the JVM exits gracefully, avoiding resource leaks and preventing hanging EMR-s jobs.
Tests:
- Reproduced the bug to confirm the issue.
- Applied the fix and verified that the driver now shuts down as expected.

Fix shutdown bug due to non-daemon thread in driver

---

build.sbt
flint-core/src/main/java/org/apache/spark/metrics/sink/CloudWatchSink.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedName.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedNameBuilder.java
flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporterTest.java
flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedNameTest.java

* Added option to include metric filter in CWSink.
* CloudWatchSDK is not available during runtime, so adding the dependency explicitly.
* Example Usage :`--conf spark.metrics.conf.*.sink.cloudwatch.regex=.*Flint.*` property would  publish only metrics with the regex Given.
* Streamlined implementation of adding dimensions to metricNames.
* No need to review DimensionedName Class: It is picked up from https://github.com/azagniotov/codahale-aggregated-metrics-cloudwatch-reporter.
Usage of Dimensioned Name for below image:
```java
final DimensionedName dimensionedName = DimensionedName
.withName("FlintOpensearchErrorCount")
.withDimension("domainIdent", "88888")
.build();
metricRegistry.counter(dimensionedName.encode()).inc();
metricRegistry.counter(derivedDimensionedName.encode()).inc(); …
```

Add dimensions to cloudwatch metric and metric filter option for CWSink.

---

spark-sql-application/src/main/scala/org/apache/spark/sql/CommandState.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

This PR reduces the frequency of 'getSessionDoc' calls in two places of FintREPL, addressing the correlation between request count and query latency metrics.
1. **Heartbeat Update Optimization**:
- Prior to updating the heartbeat, the sequence number and primary term are now obtained for effective concurrency control.
- This PR removes the get session doc call and directly updates the last update time and state.
2. **Session Document Retrieval before Statement Processing**:
- Previously, in scenarios where a query takes 10 minutes, the 'getSessionDoc' call is limited to once per 10 minutes. However, in idle states with no running queries, the call frequency is run every 100 milliseconds. 
-  This PR reduced the frequency of 'getSessionDoc' calls by ensuring we make the call at least 1 …

Reduce Session Document Retrieval in FintREPL to Enhance Latency Metrics

---

MAINTAINERS.md

Our workflow for checking maintainers file against codeowners checks the username in the square brackets. I've updated this accordingly. 
N/A

Fixed the GitHub id column for Yang-DB in Maintainers

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala

1.  Fix bug of array type support when create materialized view. Instead of using `array` using `array<elementType>`.
2. Add data type mapping between spark datatype and OpenSearch datatype.
* Spark ArrayType<ElementType> map to ElementType in OpenSearch
* Spark BinaryType map to binary type in OpenSearch
#112 

bug fix, support array datatype in MV

---

flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala

* percent-encode invalid flint index characters
Signed-off-by: Sean Kao <seankao@amazon.com>
* formatting
Signed-off-by: Sean Kao <seankao@amazon.com>
* move encoding logic to FlintOpenSearchClient
Signed-off-by: Sean Kao <seankao@amazon.com>
* minor arg fix and string format fix
Signed-off-by: Sean Kao <seankao@amazon.com>
* fix import order
Signed-off-by: Sean Kao <seankao@amazon.com>
---------
Signed-off-by: Sean Kao <seankao@amazon.com>
(cherry picked from commit 3528b6660f7f1ddb2fbb9d0af8a0748e545424e3)
For more information on following Developer Certificate of Origin and …

[Backport 0.1] Percent-encode invalid flint index characters (#215)

---

.github/workflows/backport.yml
.github/workflows/snapshot-publish.yml

* Fix backport GHA tries to skip non-existent file `CHANGELOG.md`
* Add target branch `0.*` to snapshot-publish

GHA fix for backport and snapshot-publish

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala

Quote table name with backticks to escape special characters in spark.read.table()
Follow up on
* #215 
which allows for creating flint index on table name with special characters, but build() on these index fails if table name not escaped by backticks (``` ` ```)

Quote table name with backticks to escape special characters in spark.read.table()

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala

Quote table name with backticks to escape special characters in spark.read.table() (#224)
* quote table name for special character in df read
Signed-off-by: Sean Kao <seankao@amazon.com>
* add UT
Signed-off-by: Sean Kao <seankao@amazon.com>
* update comments; scalafmtAll
Signed-off-by: Sean Kao <seankao@amazon.com>
* add a missed table name to quote
Signed-off-by: Sean Kao <seankao@amazon.com>
---------
Signed-off-by: Sean Kao <seankao@amazon.com>
(cherry picked from commit 6e163e77a2d8598ad105835f3ce20677d84fea84)
For more information on following Developer Certificate of Origin …

[Backport 0.1] Quote table name with backticks to escape special characters in spark.read.table()

---

docs/index.md
flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategy.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/valueset/ValueSetSkippingStrategySuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala

This is a follow-up PR after https://github.com/opensearch-project/opensearch-spark/pull/208 to support algorithm parameters in skipping index SQL statement. Currently this is only applied to ValueSet and will be useful for BloomFilter skip type in future. Updated user manual: https://github.com/dai-chen/opensearch-spark/blob/configure-value-set-limit-in-ddl/docs/index.md#skipping-index
- https://github.com/opensearch-project/opensearch-spark/issues/197
- https://github.com/opensearch-project/opensearch-spark/issues/202 …

Configure value set max size in SQL statement

---

docs/index.md
flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexNameITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala

This is a follow-up PR after https://github.com/opensearch-project/opensearch-spark/pull/189 which changes the semantic of delete index API from physical to logical delete.
https://github.com/opensearch-project/opensearch-spark/issues/104

Change delete index API to logical delete

---

.github/workflows/backport.yml

Context:
This [PR](https://github.com/opensearch-project/opensearch-spark/actions/runs/7587593648/job/20668300157?pr=209) has a backport label before merged, which failed the backport workflow. To fix this, we need to trigger barkport workflow when a pull request merges
Ref https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/backport.yml#L12-L22
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-o …

Trigger barkport workflow when a pull request merges

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedName.java
flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporterTest.java
flint-core/src/test/java/opensearch/flint/core/metrics/reporter/DimensionedNameTest.java

* Added FlintMetricSource, which will be used in upcoming PRs for publish all kinds of metrics.
* Added default dimensions of domainId, jobId, applicationId while publishing metrics in CloudWatch Sink.
* Removed prefixes appended to metricNames. For eg:
Previous Metric Name: 
**driver.00fg29jd50i99g0m.LiveListenerBus.queue.appStatus.listenerProcessingTime**
Current Metric Name:
**LiveListenerBus.queue.appStatus.listenerProcessingTime** 
* Changed the separator in DimensionedName encoder to "##" to remove conflicts with names containing ": "
Sample Metrics Testing:
For more information on following Developer …

Changes for adding default dimensions in CWSink.

---

docs/index.md
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala

This PR primarily removes the `refreshMode` in the `refreshIndex()` API, which is internally used by the SQL layer. This change serves as a prerequisite for follow-up changes that introduce Manual-Incremental refresh mode for https://github.com/opensearch-project/opensearch-spark/issues/195.
Currently, Flint SQL layer always pass the following mode to refresh index API layer:
- `INCREMENTAL` mode if `CREATE INDEX ... WITH (auto_refresh=true)`
- `FULL` mode if `REFRESH INDEX` statement
The revision clarifies that the **refresh mode is inherently a characteristic of the Flint index upon creation**, rather than something that can be specified later through either the `refreshIndex` API or the `REFRESH` statement. In other words, the `refreshIndex` API will autonomously determine the mode by …

Refactor Flint index refresh mode

---

.github/workflows/link-checker.yml
.lychee.excludes

Link Checker was failed after running 6 hours. For eample:
https://github.com/opensearch-project/opensearch-spark/actions/runs/7467796452/job/20321992067
https://github.com/opensearch-project/opensearch-spark/actions/runs/7633124566/job/20794704865
Trying to fix this issue following to some best practice. Ref https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/links.yml

Fix Lychee Link Checker Error

---

docs/index.md
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

To address the 2 issues related:
1. Quick fixed recover index API to clean up metadata log entry if Flint data index is gone. This prevents index stuck in refreshing state and infinite attempt on recover index API.
2. Added check to prevent FlintJob hang even though no streaming job launched by recover statement.
Updated user manual: https://github.com/dai-chen/opensearch-spark/blob/fix-recover-index-for-index-data-deleted/docs/index.md#index-job-management
1. Integration test with FlintJob *[Checking with @kaituo if possible to add IT]*
3. https://github.com/opensearch-project/opensearch-spark/issues/244
Manual test to double confirm. First of all, replicate the problematic scenario as outlined below:
<pre>
CREATE SKIPPING INDEX ON stream.lineitem_tiny
(l_shipdate VALUE_SET)
WITH ( …

Fix recover index bug when Flint data index is deleted accidentally

---

build.sbt
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchQueryReader.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchReader.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/reporter/DimensionUtilsTest.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
integ-test/src/test/scala/org/apache/spark/sql/JobTest.scala
integ-test/src/test/scala/org/apache/spark/sql/REPLResult.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLCorrelationITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/EnvironmentProvider.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/RealEnvironment.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/util/MockEnvironment.scala

This PR introduces a bug fix and enhancements to FlintREPL's session management and optimizes query execution methods. It addresses a specific issue where marking a session as 'dead' inadvertently triggered the creation of a new, unnecessary session. This behavior resulted in the new session entering a spin-wait state, leading to duplicate jobs.
The improvements include:
- **Introduction of `earlyExitFlag`**: A new flag, `earlyExitFlag`, has been introduced and is set to `true` under two conditions: when a job is excluded or when it is not associated with the current session's job run ID. This flag is evaluated in the shutdown hook to determine whether the session state should be marked as 'dead'. This change effectively prevents the unintended creation of duplicate sessions by the SQL …

Fix Session state bug and improve Query Efficiency in REPL

---

build.sbt
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchQueryReader.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchReader.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/app/FlintInstance.scala
integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
integ-test/src/test/scala/org/apache/spark/sql/JobTest.scala
integ-test/src/test/scala/org/apache/spark/sql/REPLResult.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/EnvironmentProvider.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/RealEnvironment.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/util/MockEnvironment.scala

* Fix Session state bug and improve Query Efficiency in REPL
This PR introduces a bug fix and enhancements to FlintREPL's session management and optimizes query execution methods. It addresses a specific issue where marking a session as 'dead' inadvertently triggered the creation of a new, unnecessary session. This behavior resulted in the new session entering a spin-wait state, leading to duplicate jobs.
The improvements include:
- **Introduction of `earlyExitFlag`**: A new flag, `earlyExitFlag`, has been introduced and is set to `true` under two conditions: when a job is excluded or when it is not associated with the current session's job run ID. This flag is evaluated in the shutdown hook to determine whether the session state should be marked as 'dead'. This change effectively …

[Backport 0.1] Fix Session state bug and improve Query Efficiency in REPL (#245)

---

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLog.java
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/OptimisticTransaction.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

Backport https://github.com/opensearch-project/opensearch-spark/commit/f4744abf38caeb4f22758f112a32c8881842efad from https://github.com/opensearch-project/opensearch-spark/pull/241.
Note that the original PR depends on metadata log purge functionality introduced in https://github.com/opensearch-project/opensearch-spark/pull/189. To avoid the possible impact and API changes, I only cherry-picked minimal code changes instead of the complete https://github.com/opensearch-project/opensearch-spark/pull/189.
<pre>
CREATE SKIPPING INDEX ON stream.lineitem_tiny
(l_shipdate VALUE_SET)
WITH ( auto_refresh = true );
<b>DELETE flint_myglue_stream_lineitem_tiny_skipping_index</b>
GET .query_execution_request_myglue/_search
{
"_index": ".query_execution_request_myglue",
"_id": …

[Backport 0.1] Fix recover index bug when Flint data index is deleted accidentally

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Metrics included in this PR:
```
"s3.error.count";
"session.running.count";
"session.failed.count";
"session.success.count";
"session.processingTime";
"statement.running.count";
"statement.failed.count";
"statement.success.count";
"statement.processingTime";
```
There are two options to calculate session and statement metrics:
Option 1 (taken in this PR): Utilizes direct instrumentation, offering simplicity. However, it lacks resilience against manual modifications to request/result indices by users.
Option 2: Implements asynchronous data retrieval from the request index, ensuring data integrity from the primary source. This introduces additional overhead and dependency, given the external nature of the index.
https://github.com/opensearch-project/opensearch-spark/issues/117
By submitting …

Add interactive job metrics

---

.gitignore
README.md
build.sbt
docs/PPL-on-Spark.md
docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintVersion.scala

Bump Flint current version to 0.3.0 in main branch
Testing
Version in artifact name:
```
$ sbt clean assembly
$ find . -name "*-0.3.0-SNAPSHOT.jar"
./spark-sql-application/target/scala-2.12/sql-job-assembly-0.3.0-SNAPSHOT.jar
./flint-spark-integration/target/scala-2.12/flint-spark-integration-assembly-0.3.0-SNAPSHOT.jar
./ppl-spark-integration/target/scala-2.12/ppl-spark-integration-assembly-0.3.0-SNAPSHOT.jar
```
Version in Flint index metadata (currently version field represents Flint code version. We can add another field specVersion for specification version as needed):
```
./bin/spark-sql --jars /Users/penghuo/oss/opensearch-spark/flint-spark-integration/target/scala-2.12/flint-spark-integration-assembly-0.3.0-SNAPSHOT.jar --conf …
```

Bump Flint version to 0.3.0

---

flint-spark-integration/src/main/resources/bloom_filter_query.script
flint-spark-integration/src/main/resources/bloom_filter_query.txt
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/storage/FlintQueryCompiler.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/storage/FlintQueryCompilerSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala

This PR introduces BloomFilter query pushdown optimization in OpenSearch by using a Painless script. Without dependency on OpenSearch SQL or another new mapper plugin, the following BloomFilter deserialization and membership check code are encoded in a Painless script https://github.com/dai-chen/opensearch-spark/blob/implement-bloom-filter-query-pushdown/flint-spark-integration/src/main/resources/bloom_filter_query.script.
```
public static BloomFilter readFrom(InputStream in) {
DataInputStream dis = new DataInputStream(in);
int version = dis.readInt();
int numHashFunctions = dis.readInt();
BitArray bits = BitArray.readFrom(dis);
...
}
public boolean mightContainLong(long item) {
int h1 = Murmur3_x86_32.hashLong(item, 0);
int h2 = Murmur3_x86_32.hashLong(item, h1);
long bitSize = …
```

Implement BloomFilter query pushdown optimization

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Move the query parameter from the entry point's main() arguments to SparkConf for batch and streaming jobs. There is no effect on interactive jobs other than removing the dummy query from the arg, which always reads from the request index.
Breaking change - together with https://github.com/opensearch-project/sql/pull/2519
https://github.com/opensearch-project/sql/issues/2376

Move query from entry point to SparkConf 

---

README.md
docs/PPL-on-Spark.md

The extension class name is not correct in the README.md.

Fix spark extension path in README.

---

docs/index.md
flint-spark-integration/src/main/antlr4/FlintSparkSqlExtensions.g4
flint-spark-integration/src/main/antlr4/SparkSqlBase.g4
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala

This PR introduces the SQL support and concludes the BloomFilter skipping index development. Please read more in user manual: https://github.com/dai-chen/opensearch-spark/blob/add-bloom-filter-sql-support/docs/index.md#skipping-index
https://github.com/opensearch-project/opensearch-spark/issues/206

Add BloomFilter skipping index SQL support

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala

Rule out the logical deleted skipping index in query rewrite. With changes in https://github.com/opensearch-project/opensearch-spark/pull/276, query writer has access to index state in log entry directly.
<pre>
spark-sql> SHOW FLINT INDEX IN myglue;
flint_myglue_ds_tables_http_logs_skipping_index  skipping  ds_tables  http_logs	NULL	false	<b>active</b>
spark-sql> EXPLAIN SELECT * FROM ds_tables.http_logs WHERE clientip = '127.0.0.1';
== Physical Plan ==
*(1) Filter (isnotnull(clientip#34) AND (clientip#34 = 127.0.0.1))
+- FileScan json ds_tables.http_logs[@timestamp#33,clientip#34,request#35,status#36,size#37,...]
Batched: false, DataFilters: [isnotnull(clientip#34), (clientip#34 = 127.0.0.1)], Format: JSON,
Location: <b>FlintSparkSkippingFileIndex</b>(1 …

Rule out logical deleted skipping index in query rewrite

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala

This PR introduced changes in Flint index factory which captured any exception occurred during Flint index creation. The invalid index will be ignored and log a warning message as below. Because all `SHOW` and `DESC` statement make use of this factory, this should fix the issue for all show and describe statements.
```
4/03/26 09:58:40 WARN FlintSparkIndexFactory: Failed to create Flint index from metadata
FlintMetadata(0.3.0,,,,[Ljava.util.Map;@4f60ac31,{},{},{},None,None,
Some({"index.creation_date":"1711472320637","index.number_of_replicas":"1","index.number_of_shards":"1",
"index.provided_name":"flint_spark_catalog_invalid_index","index.uuid":"NUWGIPFjQqO_2hn6pF94_w",
"index.version.created":"136277827"}))
scala.MatchError:  (of class java.lang.String)
at …
```

Ignore non-Flint index in show and describe index statement

---

flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/auth/AWSRequestSigningApacheInterceptor.java
flint-core/src/main/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptor.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-core/src/test/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptorTest.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala

Add AWS credentials provider for metadata access
Sample log for POC purpose
```
24/03/15 00:05:51 INFO OpenSearchUpdater: Checking if index exists: flint_ql_sessions
24/03/15 00:05:51 INFO AWSRequestSigningApacheInterceptor: POC - sign - use superAdminAWSCredentialsProvider
24/03/15 00:05:51 INFO HttpStatusCodeResultPredicate: Checking if status code is retryable: 200
24/03/15 00:05:51 INFO HttpStatusCodeResultPredicate: Status code 200 check result: false
24/03/15 00:05:51 INFO AWSRequestSigningApacheInterceptor: POC - sign - use superAdminAWSCredentialsProvider
24/03/15 00:05:52 INFO HttpStatusCodeResultPredicate: Checking if status code is retryable: 200
24/03/15 00:05:52 INFO HttpStatusCodeResultPredicate: Status code 200 check result: false
24/03/15 00:05:52 INFO FlintREPL: Updated …
```

Add AWS credentials provider for metadata access

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

In [a previous PR in sql](https://github.com/opensearch-project/sql/pull/2587), query is escaped in spark submit parameter. This PR unescapes the query on the receiving end, retrieving the original query. This affects only the query in SparkConf.
End to end test is performed as follows:
Query:
```
CREATE INDEX cv
ON mys3.default.http_logs (`status`, `day`, `size`, `request`)
WITH (
auto_refresh = true,
refresh_interval="5 Minutes",
checkpoint_location = 's3://test',
index_settings = "{\"number_of_shards\":1,\"number_of_replicas\":1}"
)
```
Spark submit parameter for the EMR job (query escaped and wrapped with quotes):
```
--conf spark.flint.job.query="CREATE INDEX cv ON mys3.default.http_logs (`status`, `day`, `size`, `request`) WITH (auto_refresh = true, refresh_interval=\"5 Minutes\", …
```

Unescape query from EMR spark submit parameter

---

build.sbt
integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintPPLSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLCorrelationITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTimeWindowITSuite.scala

This change adds the capability to run integration tests on iceberg tables. 
```
sbt "integtest/test" 
[info] Run completed in 34 minutes, 32 seconds.
[info] Total number of tests run: 302
[info] Suites: completed 29, aborted 0
[info] Tests: succeeded 302, failed 0, canceled 0, ignored 1, pending 0
[info] All tests passed.
```

Adding support to run integ tests on iceberg tables

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkValidationHelper.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/IncrementalIndexRefresh.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexValidationITSuite.scala

The pre-validation of checkpoint locations, introduced in [PR #297](https://github.com/opensearch-project/opensearch-spark/pull/297), requires the specified checkpoint path to exist. However, Spark is designed to automatically create necessary sub-folders when a streaming job begins. This PR is to relax this strict validation to enhance user convenience and ensure backward compatibility.
For checkpoint location without access permission, the behavior is the same as before:
<pre>
spark-sql> CREATE SKIPPING INDEX ON ds_tables.http_logs 
...                (clientip VALUE_SET) 
...                WITH (
...                  auto_refresh = true,
...                  <b>checkpoint_location = 's3://test/test'</b>
...                );
java.lang.IllegalArgumentException: requirement failed: 
No …

Allow non-existent checkpoint location path in index validation

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/ShuffleCleaner.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/util/CleanerFactoryTest.scala

* For REPL, clean shuffle data after query result is consumed.
* For Index/MV Refresh Job, clean shuffle data after each microBatch.
https://github.com/opensearch-project/opensearch-spark/issues/302

Clean shuffle data

---

build.sbt
flint-core/src/main/scala/org/opensearch/flint/core/auth/AWSRequestSigV4ASigningApacheInterceptor.java
flint-core/src/main/scala/org/opensearch/flint/core/auth/AWSRequestSigningApacheInterceptor.java
flint-core/src/main/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptor.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-core/src/test/scala/org/opensearch/flint/core/auth/AWSRequestSigV4ASigningApacheInterceptorTest.java
flint-core/src/test/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptorTest.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

* Introduce `AWSRequestSigV4ASigningApacheInterceptor` to sign metadata access with sigV4a
* Refactor `ResourceBasedAWSRequestSigningApacheInterceptor` interface
Current signer:
```
24/04/04 20:53:48 INFO AWSRequestSigningApacheInterceptor: unsigned request: GET /query_results2?master_timeout=30s&ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false HTTP/1.1 [Content-Length: 0, Host: xxx, Connection: Keep-Alive, User-Agent: Apache-HttpAsyncClient/4.1.5 (Java/17.0.9)]
24/04/04 20:53:48 INFO AWSRequestSigningApacheInterceptor: signed request: GET /query_results2?master_timeout=30s&ignore_throttled=false&ignore_unavailable=false&expand_wildcards=open%2Cclosed&allow_no_indices=false HTTP/1.1 [Authorization: AWS4-HMAC-SHA256 Credential=xxx, …
```

Introduce aws sigv4a request signer

---

build.sbt
docs/index.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkOptimizer.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergCoveringIndexITSuite.scala

This PR introduces the feature to rewrite applicable queries using covering indexes, enhancing the performance of SELECT queries by allowing faster data retrieval using these indexes.
- Implemented query rewrite logic that detects when a covering index can be utilized for a query.
- Added new SQL test cases to ensure proper functionality and to validate that queries are only rewritten when appropriate indexes are available and enabled.
- Provided a new option to enable or disable query rewrites using covering indexes.
Added several unit and integration tests to cover:
- UT: The basic functionality of query rewrite when a suitable covering index exists.
- IT: Ensuring no rewrite occurs when covering indexes are disabled via Spark configuration.
- IT: Correct interaction of query rewrites …

Add covering index based query rewriter rule

---

integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala

* add a new conf `spark.flint.streaming.dynamicAllocation.maxExecutors` (default 10) to control streaming query max executors count. it will override spark.dynamicAllocation.maxExecutors.
* it is short-term solution, in long-term client application should configure `spark.dynamicAllocation.maxExecutors` directly. Track with https://github.com/opensearch-project/sql/issues/2641
* test with EMR-S
* spark.flint.streaming.dynamicAllocation.maxExecutors = 5, max 5 executors allocated for streaming query.
* no setting, max 10 executors allocated for streaming query.
https://github.com/opensearch-project/opensearch-spark/issues/324
For more information on following Developer …

Add maxExecutors configuration for streaming queries

---

build.sbt
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Improve flint error handling
* Add jobType in result metadata
* Refactor error field format of result metadata
* Redact sensitive info for Glue AccessDeniedException in error message
* Add service name in error field of result metadata
* Add status code in error field of result metadata 
* Remove unused params in `handleQueryException`

Improve flint error handling

---

build.sbt
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintJobTest.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

* Improve flint error handling
Signed-off-by: Louis Chu <clingzhi@amazon.com>
* Error field in json format
Signed-off-by: Louis Chu <clingzhi@amazon.com>
* Superset update
Signed-off-by: Louis Chu <clingzhi@amazon.com>
---------
Signed-off-by: Louis Chu <clingzhi@amazon.com>
(cherry picked from commit 45835cb27407166669f660cc665436ed6cc93200)

[Manual Backport 0.3] Improve flint error handling (#335)

---

flint-core/src/main/java/org/opensearch/flint/core/IRestHighLevelClient.java
flint-core/src/main/java/org/opensearch/flint/core/logging/CustomLogging.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala

Apply new logging format to record actions
1. LogInfo on JobType
```
24/05/13 20:46:11 INFO CustomLogging: {"timestamp":1715633171427,"severityText":"INFO","severityNumber":9,"body":{"message":"Job type is: interactive"},"attributes":{"domainName":"xxxxxx","clientId":"xxxxxx"}}
```
2. LogError on exist errors in FlintREPL and FlintJob interface
```
24/05/13 20:46:39 ERROR CustomLogging: {"timestamp":1715633199579,"severityText":"ERROR","severityNumber":17,"body":{"message":"OpenSearch Operation failed with an exception:"},"attributes":{"domainName":"xxxxxx","clientId":"xxxxxx","exception.type":"java.net.ConnectException","exception.message":"Timeout connecting to xxxxxx"}}
```
3. Glue info redaction
```
{"Message":"Fail to read data from Glue. Cause: Access denied in AWS Glue service. …
```

Apply new logging format to record exceptions

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/FlintSparkSqlAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/index/FlintSparkIndexAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala

This PR addresses the issue reported in #330, where `SHOW INDEX` and similar SQL statements returned index names associated with unintended tables due to same prefix in Flint index names. The underlying bug has been resolved by adding an additional validation step to verify catalog/database or the source table name after `describeIndex()`. This is fixed in Flint SQL layer, because the `describeIndex()` API is generic and accepts Flint index name.
Examples:
```
spark-sql> SHOW FLINT INDEX IN myglue.ds_tables;
flint_myglue_ds_tables_http_logs_all_index	covering	ds_tables	http_logs	all	false	active
flint_myglue_ds_tables_http_logs_lf_clientip_and_request_index	covering	ds_tables	http_logs_lf	clientip_and_request	false	active
flint_myglue_ds_tables_http_logs_lf_hive_all_index	covering …
```

Fix incorrect result in show index statement

---

README.md
build.sbt
docs/PPL-on-Spark.md
docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintVersion.scala

Bumped Flint version to 0.5.0. Ref: https://github.com/opensearch-project/opensearch-spark/pull/311
Testing:
```
$ sbt clean assembly
$ find . -name "*-0.4.0-SNAPSHOT.jar"
$ find . -name "*-0.5.0-SNAPSHOT.jar"
./integ-test/target/scala-2.12/integ-test-assembly-0.5.0-SNAPSHOT.jar
./spark-sql-application/target/scala-2.12/sql-job-assembly-0.5.0-SNAPSHOT.jar
./flint-spark-integration/target/scala-2.12/flint-spark-integration-assembly-0.5.0-SNAPSHOT.jar
./ppl-spark-integration/target/scala-2.12/ppl-spark-integration-assembly-0.5.0-SNAPSHOT.jar
```
N/A …

Bump Flint version to 0.5.0

---

docs/index.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala

This PR introduces enhancements to the `FlintSparkIndexMonitor` to improve the robustness and observability of index monitoring tasks. By tracking consecutive errors, this update helps in better managing the streaming tasks and resource utilization.
1. Add new Spark conf for monitor initial delay, interval and max error count
2. Add `FlintSparkIndexMonitorTask` with counter tracking number of consecutive errors
3. Add streaming job and monitor task terminating logic once max error count reached
Testing with EMR and AOS:
<pre>
scala> sc.setLogLevel("INFO")
<b># Start index refresh streaming job</b>
sql("CREATE SKIPPING INDEX ON myglue.ds_tables.http_logs_perf_tiny (status VALUE_SET) WITH (auto_refresh = true)")
24/05/17 21:28:13 INFO FlintSparkIndexMonitor: Starting index monitor for …

Enhance index monitor to terminate streaming job on consecutive errors

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingStrategy.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSkippingIndexITSuite.scala

1. re-enable Iceberg Skipping IT and MV IT.
2. for skipping index, extract read-padding col and push down, revert IT ''can build skipping index for varchar and char and rewrite applicable query"
https://github.com/opensearch-project/opensearch-spark/issues/331

Fix skipping index IT for char column and re-enable Iceberg IT

---

build.sbt
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintWrite.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingFileIndexSuite.scala
integ-test/src/test/scala/org/apache/spark/FlintDataSourceV2ITSuite.scala

1. Bumped Spark version to `3.5.1`
2. Fixed compiling error. Ref: https://github.com/opensearch-project/opensearch-spark/pull/351
3. Fixed broken IT
https://github.com/opensearch-project/opensearch-spark/issues/352

Bump Spark version to 3.5.1

---

README.md
build.sbt
docs/PPL-on-Spark.md
docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintVersion.scala

Bumped Flint version to 0.4.1. Ref: https://github.com/opensearch-project/opensearch-spark/pull/343
Testing:
```
$ sbt clean assembly
$ find . -name "*-0.4.0-SNAPSHOT.jar"
$ find . -name "*-0.4.1-SNAPSHOT.jar"
./integ-test/target/scala-2.12/integ-test-assembly-0.4.1-SNAPSHOT.jar
./spark-sql-application/target/scala-2.12/sql-job-assembly-0.4.1-SNAPSHOT.jar
./flint-spark-integration/target/scala-2.12/flint-spark-integration-assembly-0.4.1-SNAPSHOT.jar
./ppl-spark-integration/target/scala-2.12/ppl-spark-integration-assembly-0.4.1-SNAPSHOT.jar
```
N/A …

Bump Flint version to 0.4.1

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

This PR addresses the issue where the index state incorrectly remains in "refreshing" after a streaming job has failed. The fix  transitions the index state before Spark application exits on its best efforts. Ref: [Flint index state transition diagram](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/index.md#index-state-transition-1)
1. `FlintJob` waits for a **global lock** in `StreamingQueryManager` using the `awaitAnyTermination` API. The Spark `StreamExecution` notifies all threads suspending on it first, and then triggers the listener and cleanup logic.
2. Consequently, it's possible that main thread (`FlintJob`) completes first and does not wait for the index monitor or the listener and cleanup logic in the `StreamExecution`, as both are daemon threads.
1. A …

Transition Flint index state to Failed upon refresh job termination

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala

Added pre-validation for duplicate check for output columns in materialized view query. The pre-validation `validateIndex()` API was introduced in PR https://github.com/opensearch-project/opensearch-spark/pull/297.
https://github.com/opensearch-project/opensearch-spark/issues/357

Pre-validate duplicate columns in materialized view query

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
integ-test/src/test/scala/org/apache/spark/sql/FlintJobITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

Addressed the issue that streaming job already exits before `awaitMonitor` API called and updated Flint index state to `FAILED`.
Note that I'm unable to reproduce this issue in IT and doubt the the delay between execute SQL query and await monitor is caused by result index write. For DDL statement, although the result is empty, we write it by DataFrame with Flint data source instead of using OpenSearch client directly. Need to confirm this and will create issue separately.
https://github.com/opensearch-project/opensearch-spark/issues/368 …

Fix index state stuck in refreshing when streaming job exits early

---

flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala

Remove `dataSourceName` from args and read from options instead.
* #371  

Read dataSourceName from `FlintOptions` and avoid passing as args

---

build.sbt
flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLog.java
flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogEntry.scala
flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogService.java
flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/OptimisticTransaction.java
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintMetadata.scala
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/FlintMetadataLogServiceBuilder.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLogService.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/skipping/FlintSparkSkippingIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala

1. Use reflection for `FlintMetadataLogServiceBuilder` to support custom implementation of `FlintMetadataLogService`
2. Read `SparkConf` for such builder
3. Make `FlintMetadataLogService` an abstract class with a constructor using `SparkConf`
4. Move interfaces to flint-commons
1. Moved files: `FlintMetadataLog`, `FlintMetadataLogEntry`, `FlintMetadataLogService`, `OptimisticTransaction`
2. Remove unused `failLogEntry` from `FlintMetadataLogEntry` (no access to org.opensearch.index namespace). Can add back in next PR when storage is abstracted away from the common `FlintMetadataLogEntry`
* #371 
For more information on following Developer Certificate of Origin and signing off …

Support custom metadata log service implementation

---

docs/img/opensearch-table.md
docs/opensearch-table.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-spark-integration/src/main/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalog.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintReadOnlyTable.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintTable.scala
flint-spark-integration/src/test/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogTest.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
integ-test/src/test/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogITSuite.scala

This PR introduces the `OpenSearchCatalog` class, enabling Apache Spark to integrate with OpenSearch as a data catalog and direct access OpenSearch Index in Spark SQL. Key features and changes include:
- **`opensearch.port`**: Default is `9200`.
- **`opensearch.scheme`**: Default is `http`. Valid values are `[http, https]`.
- **`opensearch.auth`**: Default is `noauth`. Valid values are `[noauth, sigv4, basic]`.
- **`opensearch.auth.username`**: Basic auth username.
- **`opensearch.auth.password`**: Basic auth password.
- **`opensearch.region`**: Default is `us-west-2`. Used only when `auth` is `sigv4`.
- **`loadTable`**: Loads a read only table from the OpenSearch index.
- **Unsupported Operations**: The following methods throw `UnsupportedOperationException`:
- `listTables`
- …

Add OpenSearchCatalog to enable direct access OpenSearch index in Spark SQL

---

build.sbt
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTimeWindowITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/common/utils/StringUtils.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/test/java/org/opensearch/sql/common/utils/StringUtilsTest.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFiltersTranslatorTestSuite.scala

Following #33 , StringUtils is copied from sql repo to ppl-spark-integration
* #260 
* #130 

Unquote text and identifiers in PPL parsing

---

flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkTransactionSupport.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionSupportSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala

Manually cherry pick https://github.com/opensearch-project/opensearch-spark/commit/0c1ec6bdf9258cf98595ade985c8d38b7b540114 from https://github.com/opensearch-project/opensearch-spark/pull/348 and fixed conflicts primarily in `FlintMetadataLogService` which is not available in `0.4` branch. Fixed this by following the old way with `FlintClient` and `dataSourceName` to start transaction.
N/A

[Backport 0.4] Enhance Flint Spark API error reporting with centralized handler

---

flint-core/src/main/java/org/opensearch/flint/core/logging/ExceptionMessages.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

handleGeneralException should handle MetaException with AccessDeniedException properly
```
24/07/03 21:34:42 INFO FlintREPL: Original exception class name: org.apache.spark.SparkException
24/07/03 21:34:42 INFO FlintREPL: Root cause exception class name: org.apache.hadoop.hive.metastore.api.MetaException
```

handle MetaException with glue AccessDeniedException

---

docs/opensearch-table.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
flint-spark-integration/src/main/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalog.scala
flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/OpenSearchTable.scala
flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/PartitionInfo.scala
flint-spark-integration/src/main/scala/org/apache/spark/opensearch/table/ShardInfo.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintPartitionReaderFactory.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintReadOnlyTable.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScan.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/FlintScanBuilder.scala
integ-test/src/test/scala/org/apache/spark/opensearch/catalog/OpenSearchCatalogITSuite.scala
integ-test/src/test/scala/org/apache/spark/opensearch/table/OpenSearchCatalogSuite.scala
integ-test/src/test/scala/org/apache/spark/opensearch/table/OpenSearchTableITSuite.scala

* A partition of an OpenSearchTable is backed by an OpenSearch Index. Each partition is split into a configurable number of shards, which are then distributed across the cluster.
* Update doc, https://github.com/penghuo/penghuo-opensearch-spark/blob/issue396/docs/opensearch-table.md#inputpartition.
* Performance test track at https://github.com/opensearch-project/opensearch-spark/issues/403.
1. Test with EMR-S. The task is scheduled based on split count. For instance, index has 5 shards, then 5 tasks are scheduled.
```
24/06/29 00:24:43 INFO DAGScheduler: Got map stage job 0 (main at NativeMethodAccessorImpl.java:0) with 5 output partitions
24/06/29 00:24:43 INFO DAGScheduler: Submitting 5 missing tasks from ShuffleMapStage 0 (MapPartitionsRDD[5] at main at …
```

support shard level split on read path

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkValidationHelper.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/IncrementalIndexRefresh.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexValidationITSuite.scala

This PR enhances the pre-validation process for checkpoint locations by adding a write permission check. Previously, only read permissions were verified. With this update, a temporary file is created at the specified location to verify write permissions.
The side effect of this change include:
1. Checkpoint folder will be created earlier than before: Previously streaming job will do it when start
2. A temporary file will remain in the checkpoint folder: This file is intentionally left undeleted to avoid requiring delete permissions, which are only necessary during the index vacuuming process after the work in https://github.com/opensearch-project/opensearch-spark/issues/102 completed.
Tested with an S3 bucket by first revoking the `PutObject` permission:
<pre>
{
"Version": "2012-10-17", …

Pre-validate checkpoint location write permission

---

build.sbt
flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLog.java
flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogEntry.scala
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintMetadataLogEntryOpenSearchConverter.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLogEntryStorageUtils.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLogService.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/FlintMetadataLogEntryOpenSearchConverterSuite.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/OpenSearchTransactionSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala

* Refactor `FlintMetadataLogEntry` to be generic to data storage
* Remove `dataSourceName` from `DefaultOptimisticTransaction`
* Move persistence logic for OpenSearch away from `FlintMetadataLogEntry` and `DefaultOptimisticTransaction` into `FlintMetadataLogEntryOpenSearchConverter`
```
FlintMetadataLogEntry(
id: String,
seqNo: Long,
primaryTerm: Long,
createTime: Long,
state: IndexState,
dataSource: String,
error: String)
```
```
FlintMetadataLogEntry(
id: String,
createTime: Long,
state: IndexState,
entryVersion: Map[String, Any],
error: String,
storageContext: Map[String, Any])
```
* `entryVersion` is used for `FlintSpark` `updateIndex`. For OpenSearch, it should specify `seqNo` and `primaryTerm`
* `storageContext` can be used to store additional context required for persistence. For …

Separate metadata log entry data model and persistence

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkQueryRewriteHelper.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndex.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala

This PR enhances the covering index query rewriter to support query optimization using partial covering indexes (indexes created with filtering conditions). To enable this, the key question is: **Does the covering index contain all rows needed by the query filter?**
The core idea is to perform a subsumption test between the filtering conditions in the covering index and those in the user query. Subsumption testing determines if **the output of one filtering condition is "broader" than the output of another**. To utilize a Flint covering index for query acceleration, the index filter must subsume the query filter.
Ideally, we could simplify the problem by checking `queryConditions AND indexConditions = queryConditions` after expression simplification. However, there is no API in Spark …

Enhance query rewriter rule to support partial covering index

---

build.sbt
flint-core/src/main/scala/org/opensearch/flint/core/auth/ResourceBasedAWSRequestSigningApacheInterceptor.java
flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintJsonHelper.scala
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchScrollReader.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchWriter.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala

* Revert OpenSearch to 2.6.
* Test with EMR-S
https://github.com/opensearch-project/opensearch-spark/issues/443
https://github.com/opensearch-project/opensearch-spark/issues/442

Revert OpenSearch Version to 2.6

---

ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java

- Remove unimplemented syntax so that frontend can utilize the .g4 files for validation/auto-complete.
- I considered comment-out, but ended up deleting them as we can refer this PR or [file in SQL plugin](https://github.com/opensearch-project/sql/blob/main/ppl/src/main/antlr/OpenSearchPPLParser.g4) to see the original implementation, and it became a bit messy when I commented out them with TODO tag.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origi …

Remove unimplemented syntax

---

DEVELOPER_GUIDE.md
build.sbt
integ-test/src/integration/scala/org/opensearch/flint/spark/aws/AWSEmrServerlessAccessTestSuite.scala

* add flintjob integration test with EMR serverless.
```
export AWS_OPENSEARCH_HOST=search-xxx.us-west-2.on.aws
export AWS_REGION=us-west-2
export AWS_EMRS_APPID=xxx
export AWS_EMRS_EXECUTION_ROLE=xxx
export AWS_S3_CODE_BUCKET=xxx
export AWS_S3_CODE_PREFIX=xxx
export AWS_OPENSEARCH_RESULT_INDEX=query_execution_result_glue
```
* enforce jackson version to comptaible with spark jackson version.
https://github.com/opensearch-project/opensearch-spark/issues/442
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin) …

Add FlintJob integration test with EMR serverless

---

integ-test/src/test/scala/org/apache/spark/sql/FlintREPLITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala

While the root cause of the exception is parsed and returned as part of the contract, the actual ex should be logged as well.
Example 1:
```
2024-07-25T22:38:43.2312843Z 24/07/25 15:38:43 ERROR CustomLogging: {"timestamp":1721947123230,"severityText":"ERROR","severityNumber":17,"body":{"message":"Fail to analyze query. Cause: Table or view not found: testTable; line 1 pos 22;\n'Project ['name, 'age]\n+- 'UnresolvedRelation [testTable], [], false\n"},"attributes":{"domainName":"UNKNOWN:UNKNOWN","clientId":"UNKNOWN","exception.type":"org.apache.spark.sql.AnalysisException","exception.message":"Table or view not found: testTable; line 1 pos 22;\n'Project ['name, 'age]\n+- 'UnresolvedRelation [testTable], [], false\n"}}
2024-07-25T22:38:43.2317673Z org.apache.spark.sql.AnalysisException: …
```

[Bugfix] Insights on query execution error

---

ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java

- Disable unsupported PPL function expressions
- booleanExpression/relevanceExpression were missed in [the previous PR](https://github.com/opensearch-project/opensearch-spark/pull/439)
- I tested with examples from integration tests in SQL plugin package, and found some more unsupported ones such as: percentile, take, and value expression such as `3 * 5` (since it is converted to Function).
- 

Disable unsupported PPL function expressions

---

DEVELOPER_GUIDE.md

Update [DEVELOPER_GUIDE.md](https://github.com/opensearch-project/opensearch-spark/blob/main/DEVELOPER_GUIDE.md) to resolve integration test failures in MacOS.
https://github.com/opensearch-project/opensearch-spark/issues/476
- [-] Implemented unit tests
- [-] Implemented tests for combination with other commands

[Doc] Checklist to fix issue "could not find Docker environment" on macOS

---

ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java

Backport https://github.com/opensearch-project/opensearch-spark/commit/98bd79a6ea1d9587d67ae761d417b0db4242a815 from https://github.com/opensearch-project/opensearch-spark/pull/478
(Automatic backport failed)

[Backport 0.4] Disable unsupported PPL function expressions (#478)

---

integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltinFunctionITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTranslator.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/DataTypeTransformer.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/LogicalPlanTestUtils.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanMathFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanStringFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTimeFunctionsTranslatorTestSuite.scala

Add a `BuiltinFunctionTranslator` to translate PPL builtin functions to Spark builtin functions in Parser.
This PR only allows the PPL-builtin functions to be translated. In another words, using non-PPL-builtin functions in PPL query will throw an exception, even they are native Spark-builtin functions. In order to support more functions in PPL, we should update the PPL builtin functions later.
For example, following PPL builtin functions will be translated to Spark builtin functions:
String functions:
> concat
> length
> like
> lower
> ltrim
> position
> rtrim
> substring
> trim
> upper
> replace
Math Functions:
> ceil
> floor
> sqrt
> ln
> pow
> mod
> abs
Arithmetic Operator:
> \+
> \-
> \*
> \/
> %
Time Functions:
> from_unixtime
> unix_timestamp
Resolves …

Translate PPL-builtin functions to Spark-builtin functions

---

integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltinFunctionITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTranslator.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFiltersTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanMathFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanStringFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTimeFunctionsTranslatorTestSuite.scala

Followup of https://github.com/opensearch-project/opensearch-spark/pull/448.
Some PPL builtin functions could not be translated to Spark builtin functions correctly due to they have different function names (signatures). This PR supports more PPL builtin functions by adding a name mapping. With this PR, following functions could be supported to translate to Spark builtin functions correctly:
> \+
> \-
> \*
> \/
> \%
> DAY_OF_WEEK
> DAY_OF_MONTH
> DAY_OF_YEAR
> WEEK_OF_YEAR
> WEEK
> MONTH_OF_YEAR
> HOUR_OF_DAY
> MINUTE_OF_HOUR
> SECOND_OF_MINUTE
> SUBDATE
> ADDDATE
> DATEDIFF
> LOCALTIME
> IS_NULL
> IS_NOT_NULL
Resolves https://github.com/opensearch-project/opensearch-spark/issues/502 
By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 …

Support more PPL builtin functions by adding a name mapping

---

integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/CommandContext.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

With default query loop execution frequency there are 3 min session idle time and 30000 / 100 = 300 additional calls to check queries waiting in the loop.
For example, on sanity IT, there are 5000 / 100 = 50 calls theoretically, and in actuality 47 calls due to the actual query execution time.
```
FlintREPL: read from flint_ql_sessions, sessionId: 10
```
On new IT "query loop should exit with inactivity timeout due to large query loop frequency," there should be no subsequent calls because the loop waits 5 seconds, which is deemed inactivity. 
https://github.com/opensearch-project/opensearch-spark/issues/397
For more information on following Developer Certificate of Origin …

Add config on query loop execution frequency

---

DEVELOPER_GUIDE.md
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchUpdater.java
integ-test/src/aws-integration/scala/org/opensearch/flint/spark/aws/AWSEmrServerlessAccessTestSuite.scala
integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/OSClient.scala

- Use refresh policy from config when calling OpenSearch APIs
- This will allow Flint to connect to OpenSearch Serverless collection. It originally use WAIT_FOR refresh policy for some requests and it failed against Serverless collection since it only accept NONE refresh policy.
- To use Serverless collection as index store, `spark.datasource.flint.write.refresh_policy=false` config needs to be specified.
- Added integration test for Serverless
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/C …

Use refresh policy from config

---

docs/PPL-Correlation-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/DescribeRelation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstStatementBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

update correlation comment as experimental
- Update correlation documentation with experimental comment and warning
- Add ppl `describe` command for describing table structure
- https://github.com/opensearch-project/opensearch-spark/issues/536

Add PPL describe command

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala

This PR adds the capability to terminate the streaming job when the associated Flint data index no longer exists. The termination is managed by the index monitor rather than the Spark streaming listener, ensuring that the job can be terminated even if it remains idle without any new micro-batches being triggered.
Please note that this PR solely addresses the termination of the streaming job and the index monitor itself. The handling of dangling metadata log entries will be addressed in the upcoming PR for [issue #356](https://github.com/opensearch-project/opensearch-spark/issues/356).
https://github.com/opensearch-project/opensearch-spark/issues/244
For more information on …

Terminate streaming job when index data is deleted

---

flint-commons/src/main/scala/org/opensearch/flint/common/model/ContextualDataStore.scala
flint-commons/src/main/scala/org/opensearch/flint/common/model/FlintStatement.scala
flint-commons/src/main/scala/org/opensearch/flint/common/model/InteractiveSession.scala
flint-commons/src/test/scala/org/opensearch/flint/common/model/InteractiveSessionTest.scala
integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/core/OpenSearchUpdaterSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

1. Add statement timeout, the dependency change is merged https://github.com/opensearch-project/sql/pull/2724
2. Fix SessionStates to align with https://github.com/opensearch-project/sql/blob/b2403ca4fa1bbba2a1ac8827b6f7aeefe48f9f32/async-query-core/src/main/java/org/opensearch/sql/spark/execution/session/SessionState.java#L18-L21
3. Move data model from flint.data to flint.common.model

Add statement timeout

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
ppl-spark-integration/README.md

Followup of PR https://github.com/opensearch-project/opensearch-spark/pull/499:
- Update document
- Update Integ-test
https://github.com/opensearch-project/opensearch-spark/issues/429

Lateral `eval` expressions are supported after Spark upgrading

---

docs/index.md
flint-core/src/main/java/org/opensearch/flint/core/RestHighLevelClientWrapper.java
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiter.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterHolder.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchClientUtils.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterHolderTest.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterTest.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala

- Add rate limiter for bulk request
- Without rate limit, it would send request until the destination OpenSearch throttle requests (especially when `NONE` refresh policy is used).
- Added config param `spark.datasource.flint.write.bulkRequestRateLimitPerNode` to specify the rate limit per node.
- The default is set to 0, which means no rate limit.

Add rate limiter for bulk request

---

docs/index.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexBuilderSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexJobITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexMonitorITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexSqlITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala

Add conf for specifying a default checkpoint location to be re-used for index creation
https://github.com/opensearch-project/opensearch-spark/issues/102

Add conf for specifying flint checkpoint location

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala

Fix distinct_count ppl stats function
Add test for distinct_count
https://github.com/opensearch-project/opensearch-spark/issues/484

Fix distinct_count ppl stats function

---

flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-data/src/main/scala/org/opensearch/flint/data/QueryState.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/NoOpQueryMetadataService.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/QueryMetadataService.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/CustomClassLoader.scala

[POC] Store state and error using QueryMetadataService

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala

No additional effort needed to support 2+ level aggregations PPL command. This PR is adding some unit tests and integ-tests for this feature.
Resolves https://github.com/opensearch-project/opensearch-spark/issues/488

Add UT and IT for 2+ level aggregations PPL command

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkCheckpoint.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkValidationHelper.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkCheckpointSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala

This PR adds functionality to delete the checkpoint folder associated with a Flint index during the vacuuming process. The new `FlintSparkCheckpoint` class wraps Spark's `CheckpointFileManager` and abstracts checkpoint management API.
Prepare for vacuum test:
<pre>
<b># Create a materialized view and cancel refreshing after a while</b>
CREATE MATERIALIZED VIEW glue.default.vacuum_checkpoint_test_2
AS
SELECT clientip
FROM glue.default.http_logs
WITH (
auto_refresh = true,
checkpoint_location = 's3://checkpoint/vacuum-checkpoint-test-2');
<b># Drop materialized view and check current status</b>
GET _cat/indices?v
green  open   flint_glue_default_vacuum_checkpoint_test_2   5   1   2982743   0    258.6mb   121.2mb
GET .query_execution_request_glue/_search
{
"_index": …

Remove checkpoint folder when vacuuming index

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexBuilderSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala

Currently, there are two ways of creating a Flint index representation:
```
1. FlintSparkIndexFactory.create
2. FlintSparkIndexBuilder.create
```
The FlintSparkIndexFactory.create method doesn't call the option() method in FlintSparkIndexBuilder. Instead, it constructs options from metadata directly:
```
val indexOptions = FlintSparkIndexOptions(
metadata.options.asScala.mapValues(_.asInstanceOf[String]).toMap)
```
This becomes problematic on the ALTER statement, which retrieves the index via describeIndex. The describeIndex method uses FlintSparkIndexFactory.create, bypassing the option() method call. As a result, the custom checkpoint location is not properly set for ALTER statements. This inconsistency needs to be addressed to ensure proper functionality across all index operations. …

Update checkpoint location on alter path

---

flint-commons/src/main/scala/org/apache/spark/sql/StatementExecutionManager.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
integ-test/src/integration/scala/org/apache/spark/sql/FlintJobITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/CommandContext.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/SingleStatementExecutionManagerImpl.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/StatementExecutionManagerImpl.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

1. Batch and Streaming query will take `queryId` from spark conf `spark.flint.job.queryId`
2.  Refactor `FlintJob` using the `FlintStatement` data model and the `StatementExecutionManager` interface, and provide `SingleStatementExecutionManager` as the `StatementExecutionManager` implementation. With this enhancement, `FlintJob` may manage the query lifecycle using these extension points. FlintJob's default behavior remains unchanged.
https://github.com/opensearch-project/opensearch-spark/issues/633
https://github.com/opensearch-project/opensearch-spark/issues/602 …

Refactor FlintJob with FlintStatement and StatementExecutionManager

---

Dockerfile
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLPatternsITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ParseStrategy.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ParseUtils.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanPatternsTranslatorTestSuite.scala

Add patterns command using the next [OpenSearch PPL functionality](https://github.com/opensearch-project/sql/blob/7e73f124e2dc63a69750c8034558d6870c46ccf9/docs/user/ppl/cmd/patterns.rst)
**Do you have any additional context?**
- https://github.com/opensearch-project/opensearch-spark/issues/408
https://github.com/opensearch-project/opensearch-spark/issues/462 

Ppl patterns command

---

flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java

- Disable timeout params for deleteIndex API only for serverless
- OpenSearch serverless does not accept `timeout` / `master_timeout` (= clusterManagerNodeTimeout) params, which is added by the RestHighLevelClient by default. (current version of `opensearch-java` library won't add it automatically, but we are still using `2.6.0` ([ref](https://github.com/opensearch-project/opensearch-spark/blob/fd3f82fc16273d47f17aa47e699aeaa8b4c3679d/build.sbt#L13-L15))
https://github.com/opensearch-project/opensearch-spark/issues/634 …

Disable timeout params for deleteIndex API only for serverless

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltinFunctionITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTranslator.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanStringFunctionsTranslatorTestSuite.scala

`ispresent` function implemented
https://github.com/opensearch-project/opensearch-spark/issues/518

ispresent implemented as function

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

fix describe ppl command to be aware of 3 parts FQN table that includes `schema.catalog.table`
- https://github.com/opensearch-project/opensearch-spark/issues/612
- 

Fix ppl describe bug #612

---

flint-commons/src/main/scala/org/opensearch/flint/common/model/FlintStatement.scala
flint-commons/src/main/scala/org/opensearch/flint/common/model/LangType.scala
integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Add langType to FlintStatement model
N/A

Add langType to FlintStatement model

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala

Adds support for serializing TimestampNTZType by considering it the same case as a TimestampType
N/A

Add support for serializing TimestampNTZType

---

flint-commons/src/main/scala/org/opensearch/flint/common/metadata/FlintIndexMetadataService.java
flint-core/src/main/scala/org/opensearch/flint/core/FlintClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchIndexMetadataService.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchIndexMetadataServiceITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkIndexDescribeITSuite.scala

`FlintIndexMetadataService` used to use index pattern (using wildcard character `*`) to fetch index metadata for indexes matching the pattern. This change makes supporting getting by pattern optional. Instead, the service could fetch index metadata for full index names.
This does not change the `FlintSpark.describeIndexes` api, which still takes an index pattern as argument.
Alternative is to not use index pattern in `FlintIndexMetadataService.getAllIndexMetadata` at all, and instead always take full index names. However, this adds number of requests overhead for services that do allow for pattern matching, e.g. OpenSearch implementation `FlintOpenSearchIndexMetadataService`. Instead of making 1 request, a pattern that matches to N indexes would require N requests to fetch their metadata, …

Optional support for getAllIndexMetadata by index pattern

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/QueryResultWriterImpl.scala

Add resultIndex to session manager extension constructor. In this case custom session manager can work with default QueryResultWriter to persist result to OpenSearch

Add resultIndex to session manager extension

---

docs/PPL-Lookup-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLLookupITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/Alias.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/BinaryExpression.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/QualifiedName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Lookup.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/SubqueryAlias.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/LookupTransformer.java

__Syntax__
```sql
| LOOKUP <lookupIndex> (<lookupMappingField> [AS <sourceMappingField>])...
[(REPLACE | APPEND) (<inputField> [AS <outputField>])...]
```
Resolves https://github.com/opensearch-project/opensearch-spark/issues/620 and parent issue https://github.com/opensearch-project/sql/issues/2651

Translate PPL `LOOKUP` Command

---

integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java

Implementation of the `case` function
https://github.com/opensearch-project/opensearch-spark/issues/645

Implementation of case function.

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/statement/Explain.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstStatementBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ArgumentFactory.java
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParser.scala
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/PPLSyntaxParser.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanCorrelationQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanDedupeTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanEvalTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFiltersTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGrokTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanMathFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanNestedQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParseTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanPatternsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanStringFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTimeFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTopAndRareQueriesTranslatorTestSuite.scala

Add explain command
https://github.com/opensearch-project/opensearch-spark/issues/556

Add explain command

---

build.sbt
flint-commons/src/main/scala/org/apache/spark/sql/QueryResultWriter.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/CommandContext.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/QueryResultWriterImpl.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/StatementExecutionManagerImpl.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Move DF reformat from `StatementExecutionManagerImpl` to `QueryResultWriterImpl` so that people use custom `StatementExecutionManager` still can work with default `QueryResultWriterImpl` and write result to OpenSearch result index for custom data source.

[REFACTOR] Move DF reformat from StatementExecutionManagerImpl to QueryResultWriterImpl

---

ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

A followup bugfix of https://github.com/opensearch-project/opensearch-spark/pull/698
Fields listed in parent projection, but they have be excluded in child. For example,
`source=t | fields - A, B | fields A, B, C` will throw *[Field A, Field B] can't be resolved*
Related to https://github.com/opensearch-project/opensearch-spark/issues/696

Re-select an excluded field should throw SyntaxCheckException

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLInSubqueryITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/InSubquery.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/PPLSyntaxParser.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanInSubqueryTranslatorTestSuite.scala

**InSubquery usage**
- `source = outer | where a in [ source = inner | fields b ]`
- `source = outer | where (a) in [ source = inner | fields b ]`
- `source = outer | where (a,b,c) in [ source = inner | fields d,e,f ]`
- `source = outer | where a not in [ source = inner | fields b ]`
- `source = outer | where (a) not in [ source = inner | fields b ]`
- `source = outer | where (a,b,c) not in [ source = inner | fields d,e,f ]`
- `source = outer | where a in [ source = inner1 | where b not in [ source = inner2 | fields c ] | fields b ]` (nested)
- `source = table1 | inner join left = l right = r on l.a = r.a AND r.a in [ source = inner | fields d ] | fields l.a, r.a, b, c` (as join filter)
_SQL Migration examples with IN-Subquery PPL:_
1. tpch q4 (in-subquery with aggregation)
```sql
select …
```

Support `InSubquery` in PPL

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanMathFunctionsTranslatorTestSuite.scala

Antler syntax extended so that PPL supports the `signum` function.
https://github.com/opensearch-project/opensearch-spark/issues/467

Antler syntax extensions related ot signum function.

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLRenameITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Rename.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanRenameTranslatorTestSuite.scala

This PR implements the rename PPL function.
https://github.com/opensearch-project/opensearch-spark/issues/509

Add rename PPL function

---

build.sbt

Use shading in Java/Scala libraries to include all classes and their transitive dependencies in the project by renaming packages and rewriting affected bytecode.

Apply shaded rules on jars

---

ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/Field.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/QualifiedName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

Signed-off-by: Lantao Jin <ltjin@amazon.com>
(cherry picked commit 7563edbb733b8b55f5a640ed80301d646f5e500c from #707)

[Backport 0.5] Re-select an excluded field should throw SyntaxCheckException

---

.github/ISSUE_TEMPLATE/ppl_command_request.md
OpenSearch-PPL-Command-Process.md
docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/README.md
docs/ppl-lang/planning/ppl-fillnull-command.md

- update a few broken links
- update documentation with planning process suggestion
- add a first `fillnull` command planning proposal

update docs & links & add planned commands docs with process suggestion

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-eval-command.md
docs/ppl-lang/ppl-where-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltinFunctionITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4

Add `isBlank` as an "alias" to `isEmpty`
https://github.com/opensearch-project/opensearch-spark/issues/513

Implement isBlank

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/README.md
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFillnullITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/FillNull.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFillnullCommandTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanRenameCommandTranslatorTestSuite.scala

Implementation of the `fillnull` command
https://github.com/opensearch-project/opensearch-spark/issues/670

Fillnull command introduced

---

flint-core/src/main/scala/org/opensearch/flint/core/metadata/FlintMetadataCache.scala
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataCacheWriter.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchMetadataCacheWriterITSuite.scala

In addition to the regular metadata storage using `FlintIndexMetadataService`, we're dual-writing additional fields, defined by `FlintMetadataCache` (RFC for better name), to the index mappings `_meta` field. It's intended for frontend users to access some crucial metadata for an index quickly without invoking another backend API call.
This PR adds such fields for all indexes, filling it with mocked data. This is intended for `0.5-nexus` branch only, to unblock frontend dev.
Later, production PRs will go to the `main` branch, by then we'll revert this PR and backport production PRs over here in `0.5-nexus`
This behavior can be enabled through spark config: `spark.flint.metadataCacheWrite.enabled` if set to true. It should be false by default. **Important**: however, for this branch I'm …

[0.5-nexus] Write mock metadata cache data to mappings _meta

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-subquery-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLScalarSubqueryITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/ScalarSubquery.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanScalarSubqueryTranslatorTestSuite.scala

**ScalarSubquery usage**
Assumptions: `a`, `b` are fields of table outer, `c`, `d` are fields of table inner,  `e`, `f` are fields of table nested
**Uncorrelated scalar subquery in Select**
- `source = outer | eval m = [ source = inner | stats max(c) ] | fields m, a`
- `source = outer | eval m = [ source = inner | stats max(c) ] + b | fields m, a`
**Uncorrelated scalar subquery in Select and Where**
- `source = outer | where a > [ source = inner | stats min(c) ] | eval m = [ source = inner | stats max(c) ] | fields m, a`
**Correlated scalar subquery in Select**
- `source = outer | eval m = [ source = inner | where outer.b = inner.d | stats max(c) ] | fields m, a`
- `source = outer | eval m = [ source = inner | where b = d | stats max(c) ] | fields m, a`
- `source = outer | eval m = [ …

Support `ScalarSubquery` PPL

---

ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFiltersTranslatorTestSuite.scala

In SQL, `AND` has higher precedence than `OR`.
Example:
```sql
SELECT *
FROM employees
WHERE department = 'HR'
OR job_title = 'Manager'
AND salary > 50000;
```
In this query, the `AND` between `job_title = 'Manager'` and `salary > 50000` is evaluated first, because `AND` has higher precedence than `OR`. It equals to
```sql
WHERE department = 'HR'
OR (job_title = 'Manager' AND salary > 50000);
```
But in PPL, this query will be evaluated with wrong order:
```sql
source=employees
| where department = 'HR' OR job_title = 'Manager' AND salary > 50000
```
was evaluated to
```sql
source=employees
| where (department = 'HR' OR job_title = 'Manager') AND salary > 50000
```
Resolve https://github.com/opensearch-project/opensearch-spark/issues/770
By submitting this pull request, I confirm that my …

AND should have higher precedence than OR in predicate expression

---

docs/ppl-lang/PPL-Example-Commands.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/RelationUtils.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

Table name `` `_CWLBasic`.default.`Canary/service.log` `` is incorrectly converted to `default` + `Canary/service` + `log`.
It should be converted to `_CWLBasic` + `default` + `Canary/service.log` as long as the table identifier is wrapped by backticks.
https://github.com/opensearch-project/opensearch-spark/issues/767

Support table identifier contains dot with backticks

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/RelationUtils.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

backport 768 bug fix to 0.5
https://github.com/opensearch-project/opensearch-spark/issues/767

[Backport 0.5] Support table identifier contains dot with backticks

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/RelationUtils.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

backport 768 bug fix to 0.5-nexus
> In this Spark version `TableIdentifier` only supports 2 parts so the catalog is implicitly taken from spark context.
https://github.com/opensearch-project/opensearch-spark/issues/767

[Backport 0.5-nexus] Support table identifier contains dot with backticks

---

ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ArgumentFactory.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

The Fields Minus Command `fields - <field list>` has been supported from https://github.com/opensearch-project/opensearch-spark/pull/698 which is required Spark 3.5.0+
But its grammar presented at the beginning of this repository created, which the `-` in `fields - <field list>` is ignored by default. So in branch 0.5-nexus whose spark version is 3.3.2 will cause data correctness issue (the command results equal to command `fields + <field list>`).
Resolves https://github.com/opensearch-project/opensearch-spark/issues/731 …

[0.5-nexus] Disable Fields Minus in grammar to avoid data correctness issue

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-subquery-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLExistsSubqueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLInSubqueryITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/subquery/ExistsSubquery.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/subquery/InSubquery.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/subquery/ScalarSubquery.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanExistsSubqueryTranslatorTestSuite.scala

**ExistsSubquery usage**
Assumptions: `a`, `b` are fields of table outer, `c`, `d` are fields of table inner,  `e`, `f` are fields of table inner2
- `source = outer | where exists [ source = inner | where a = c ]`
- `source = outer | where not exists [ source = inner | where a = c ]`
- `source = outer | where exists [ source = inner | where a = c and b = d ]`
- `source = outer | where not exists [ source = inner | where a = c and b = d ]`
- `source = outer | where exists [ source = inner1 | where a = c and exists [ source = inner2 | where c = e ] ]` (nested)
- `source = outer | where exists [ source = inner1 | where a = c | where exists [ source = inner2 | where c = e ] ]` (nested)
- `source = outer | where exists [ source = inner | where c > 10 ]` (uncorrelated exists)
- `source = outer …

Support `ExistsSubquery` in PPL

---

build.sbt
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
flint-core/src/main/scala/apache/spark/metrics/source/FlintMetricSource.scala
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/IncrementalIndexRefresh.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/util/RefreshMetricsAspect.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/util/RefreshMetricsHelper.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/AsyncQuerySchedulerBuilder.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/FlintSparkJobExternalSchedulingService.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/FlintSparkJobInternalSchedulingService.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/FlintSparkJobSchedulingService.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/util/RefreshQueryGenerator.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexBuilderSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/scheduler/util/RefreshQueryGeneratorSuite.scala
integ-test/src/integration/scala/org/apache/spark/sql/FlintJobITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala

1. Support recovery for index with external scheduler
2. Support `ALTER` scheduler_mode between internal and external in single statement
3. Add index level metrics for refresh query, with dimension (clientId, dataSource, indexName)
4. Support external scheduler with index name including `-`
5. optimize `build.sbt` on dependency package complie
https://github.com/opensearch-project/opensearch-spark/issues/762

Support recovery for index with external scheduler

---

build.sbt

Add auth-crt lib as runtime dependency
The fat jar doesn't include auth-crt lib will cause runtime issue:
```
java.lang.NoClassDefFoundError: software/amazon/awssdk/authcrt/signer/AwsCrtV4aSigner
```
after this change:
```
Searching in /usr/lib/spark/jars/opensearch-spark-sql-application_2.12-latest.jar
software/amazon/awssdk/authcrt/signer/AwsCrtV4aSigner$Builder.class
software/amazon/awssdk/authcrt/signer/AwsCrtV4aSigner.class
software/amazon/awssdk/authcrt/signer/internal/DefaultAwsCrtV4aSigner$1.class
software/amazon/awssdk/authcrt/signer/internal/DefaultAwsCrtV4aSigner$BuilderImpl.class
software/amazon/awssdk/authcrt/signer/internal/DefaultAwsCrtV4aSigner.class
```
For …

Add auth-crt lib as runtime dependency

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexMonitor.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkTransactionSupport.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkTransactionSupportSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala

This PR introduces a lazy approach to handling potentially corrupted indices. Previously only `recoverIndex` API has such capability introduced in https://github.com/opensearch-project/opensearch-spark/pull/241 and this PR makes this logic generic across all Flint APIs.
A corrupted index is defined as a Flint index **has an index log entry but no corresponding data index**. Upon the next Flint API call, the system will check for such corrupted indices and perform the necessary cleanup, ensuring that users can recreate indices without encountering errors.
The most common scenario this PR aims to address is:
1. Users delete OS data index for a Flint index directly
2. Index monitor terminates streaming job if auto refresh enabled
3. Users attempt to create index again
a. **Before changes**: …

Lazy clean up dangling index metadata log entry

---

.github/workflows/test-and-build-workflow.yml

Even the current build strategy is `fail-fast: false` (matrix level), thanks to `jobs.<job_id>.continue-on-error` is false as default, style check fail out with an notification before Integ Test could be time saving.
https://github.com/opensearch-project/opensearch-spark/issues/782

[Infrastructure] Move style check ahead of Integ test

---

README.md
build.sbt
docs/PPL-on-Spark.md
docs/index.md
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

Bumped Flint version to 0.5.1. Ref: https://github.com/opensearch-project/opensearch-spark/pull/360
$ sbt clean assembly
$ find . -name "*-0.5.0-SNAPSHOT.jar"
$ find . -name "*-0.5.1-SNAPSHOT.jar"
```
% find . -name "*-0.5.1-SNAPSHOT.jar"
./integ-test/target/scala-2.12/integ-test-assembly-0.5.1-SNAPSHOT.jar
./spark-sql-application/target/scala-2.12/sql-job-assembly-0.5.1-SNAPSHOT.jar
./flint-spark-integration/target/scala-2.12/flint-spark-integration-assembly-0.5.1-SNAPSHOT.jar
./ppl-spark-integration/target/scala-2.12/ppl-spark-integration-assembly-0.5.1-SNAPSHOT.jar
./flint-commons/target/scala-2.12/flint-commons-assembly-0.5.1-SNAPSHOT.jar
```
For more information on …

Bump Flint version to 0.5.1

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-search-command.md
docs/ppl-lang/ppl-subquery-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLExistsSubqueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLInSubqueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLJoinITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLScalarSubqueryITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala

**(Relation) Subquery usage**
`InSubquery`, `ExistsSubquery` and `ScalarSubquery` are all subquery expressions. But `RelationSubquery` is not a subquery expression, it is a subquery plan which is common used in Join or Search/From clause.
- `source = table1 | join left = l right = r [ source = table2 | where d > 10 | head 5 ]` (subquery in join right side)
- `source = [ source = table1 | join left = l right = r [ source = table2 | where d > 10 | head 5 ] | stats count(a) by b ] as outer | head 1`
**_SQL Migration examples with Subquery PPL:_**
tpch q13
```sql
select
c_count,
count(*) as custdist
from
(
select
c_custkey,
count(o_orderkey) as c_count
from
customer left outer join orders on
c_custkey = o_custkey
and o_comment not like '%special%requests%'
group by
c_custkey
) as c_orders …
```

Support `RelationSubquery` PPL

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/README.md
docs/ppl-lang/ppl-comment.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLCommentITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

Adding both block comment `/* ... */` and line comment `//` support for PPL.
For example:
```
source=otel_logs /* Timestamped text record generated by OpenTelemetry framework */
| where kind = 'SPAN_KIND_CLIENT' // only calculate on client
| eval r = 0.99  /* precision */ | stats sum(droppedEventsCount * r) as lostEvents
```
https://github.com/opensearch-project/opensearch-spark/issues/791

Support line comment and block comment in PPL

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

- Add query execution metrics
- batch.processingTime: execution duration for batch query.
- query.execution.processingTime: Duration from start to complete query (excluding writing result)
n/a

Add query execution metrics

---

.github/CODEOWNERS
MAINTAINERS.md

Add Tomo as maintainer based on commitee vote results

Add Tomo as maintainer

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/FlintSparkJobInternalSchedulingService.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/FlintSparkJobSchedulingService.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexBuilderSuite.scala

Resolution for previous concurrency issue

Resolution for previous concurrency issue

---

build.sbt
flint-core/src/main/java/org/opensearch/flint/core/metrics/HistoricGauge.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
flint-core/src/main/scala/org/opensearch/flint/core/metrics/ReadWriteBytesSparkListener.scala
flint-core/src/test/java/org/opensearch/flint/core/metrics/HistoricGaugeTest.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

- Add read/write bytes metrics
- It uses SparkListener to collect read/write bytes/records for each task, and emit the sum once query completes.
- Added HistoricGauge to emit each data points separately with timestamp.
- Codahale stores metrics and those are emitted periodically. If application emit metrics multiple times within a period, those datapoints would be summarized or simply ignored other than last value. It is not ideal when we want to track each datapoints (such as when we want to gather metrics for each API call, etc.).
- HistoricGausge stores each data point with timestamp, and emit each data points to CW using those timestamps.
- Replaced QueryExecutionTimeMetric with HistoricGauge
Sample metrics:
n/a
By submitting this pull request, I confirm that my contribution is made …

Add read/write bytes metrics

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/README.md
docs/ppl-lang/ppl-eventstats-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEventstatsITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Window.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/WindowSpecTransformer.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanEventstatsTranslatorTestSuite.scala

The `eventstats` command enriches your event data with calculated summary statistics. It operates by analyzing specified fields within your events, computing various statistical measures, and then appending these results as new fields to each original event.
Key aspects of `eventstats`:
1. It performs calculations across the entire result set or within defined groups.
2. The original events remain intact, with new fields added to contain the statistical results.
3. The command is particularly useful for comparative analysis, identifying outliers, or providing additional context to individual events.
The `stats` and `eventstats` commands are both used for calculating statistics, but they have some key differences in how they operate and what they produce:
- Output Format:
- `stats`: …

Support `Eventstats` in PPL

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkCheckpoint.scala

- Add checkpoint.delete.processingTime metric
Tested in my test cluster
n/a

Add checkpoint.delete.processingTime metric

---

flint-core/src/main/java/org/opensearch/flint/core/IRestHighLevelClient.java
flint-core/src/main/java/org/opensearch/flint/core/RestHighLevelClientWrapper.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/HistoricGauge.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkRetryWrapper.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsTestUtil.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/OpenSearchBulkRetryWrapperTest.java

- Add OpenSearch related metrics
- Separate metrics for create/search/bulk APIs (read/write metrics will continue including them)
- Retry metrics for bulk (retry count, all retry failed)
- Latency metric for each call
- 429 (throttling) as separate metric
Tested metric emission in my test cluster
n/a

Add opensearch related metrics

---

.github/pull_request_template.md
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedName.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedNameBuilder.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiter.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterHolder.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkRetryWrapper.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchUpdater.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/reporter/DimensionedNameTest.java
flint-core/src/test/scala/org/opensearch/flint/core/auth/AWSRequestSigningApacheInterceptorTest.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterHolderTest.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterTest.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/OpenSearchBulkRetryWrapperTest.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/FieldsMapping.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/IsEmpty.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/Scope.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Correlation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/FillNull.java
ppl-spark-integration/src/main/java/org/opensearch/sql/common/antlr/Parser.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/JoinSpecTransformer.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/ParseStrategy.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/RelationUtils.java
spark-sql-application/src/main/java/org/opensearch/sql/FlintDelegatingSessionCatalog.java

Fix copyright header missing
Resolves https://github.com/opensearch-project/opensearch-spark/issues/812

Fix copyright header missing

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala

`Count()`, as is `count(*)` in SQL, cannot be resolved correctly when it located after other fields resolution.
For example:
```
source = $testTable | eval a = 1 | stats sum(a) as sum, avg(a) as avg, count() as cnt by country
```
Throws 
> [NESTED_AGGREGATE_FUNCTION] It is not allowed to use an aggregate function in the argument of another aggregate function. Please use the inner aggregate function in a sub-query.;
> Project [sum#31L, cnt#33L, country#34]
> +- Aggregate [country#38], [sum(a#30) AS sum#31L, count(avg(a#30)) AS cnt#33L, country#38 AS country#34]
>    +- Project [name#35, age#36, state#37, country#38, year#39, month#40, 1 AS a#30]
>       +- SubqueryAlias spark_catalog.default.flint_ppl_test
>          +- Relation spark_catalog.default.flint_ppl_test[name#35,age#36,state#37,c …

`All-fields` as an argument of aggregator such as count() can be resolved after other `field`

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/functions/ppl-expressions.md
docs/ppl-lang/ppl-eval-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLEvalITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanEvalTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFiltersTranslatorTestSuite.scala

IN expression doesn't work in PPL:
`| where state in ('California', 'Florida')` throws NPE
This PR targets to support following syntax:
- `value IN (value_list)`
- `value NOT IN (value_list)`
- `NOT value IN (value_list)` to compatible with opensearch-sql
Resolves https://github.com/opensearch-project/opensearch-spark/issues/822

Support IN expression in PPL

---

ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java

This PR is sourcing from fixing the problem introduced by https://github.com/opensearch-project/opensearch-spark/pull/723:
`| stats sum(1) as value` failed due to https://github.com/opensearch-project/opensearch-spark/pull/723 introduced a keyword `VALUE` but not marked as Id in ANTLR file.
Then I identified there are not only `VALUE`, but also more invalid keywords as identifier in g4 file.
Resolves https://github.com/opensearch-project/opensearch-spark/issues/820
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate-of-origin …

Fix the issue that missing identifiers from ANTLR keywords

---

.gitignore
docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/planning/ppl-between.md
docs/ppl-lang/ppl-where-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBetweenITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBetweenExpressionTranslatorTestSuite.scala

Add PPL Between functionality
https://github.com/opensearch-project/opensearch-spark/issues/679

Add PPL Between functionality

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
flint-core/src/test/java/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransactionMetricTest.java

- Add index state metrics
- `indexState. updatedTo.{state}.count`: count for the index's final log state. emitted after optimistic transaction when it is successful.
- `initialConditionCheck.failed.{state}.count`: count for initial condition check failure per index state.
Tested with creating auto refresh MV, and trying manual refresh:
n/a

Add index state metrics

---

build.sbt
flint-core/src/main/java/org/opensearch/flint/core/metrics/HistoricGauge.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricsUtil.java
flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java
flint-core/src/main/scala/org/opensearch/flint/core/metrics/ReadWriteBytesSparkListener.scala
flint-core/src/test/java/org/opensearch/flint/core/metrics/HistoricGaugeTest.java
flint-core/src/test/java/org/opensearch/flint/core/metrics/MetricsUtilTest.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/refresh/AutoIndexRefresh.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

Manually backport https://github.com/opensearch-project/opensearch-spark/commit/2a647d43264cdcbb65f95b22c8373dee50497937 from https://github.com/opensearch-project/opensearch-spark/pull/803
Auto backport failed due to conflict in build.sbt

[Manual Backport 0.5-nexus] Add read/write bytes metrics (#803)

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/StatementExecutionManagerImpl.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Optimize prepareStatementExecution request freq. 
Before the change:
- prepareStatementExecution will run k times, depends dynamically on session duration and query execution time.
- getNext will run k times to create new reader clients
After the change:
- prepareStatementExecution will run 1 time before the query loop
- getNext will behave the same, to avoid concurrent issue of using one reader client within same session 
Also tested on EMR to verify number of times.
https://github.com/opensearch-project/opensearch-spark/issues/804 …

Optimize prepareStatementExecution request freq

---

docs/index.md
flint-commons/src/main/scala/org/opensearch/flint/common/metadata/log/FlintMetadataLogEntry.scala
flint-core/src/main/scala/org/opensearch/flint/core/metadata/log/DefaultOptimisticTransaction.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintMetadataLogEntryOpenSearchConverter.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchMetadataLog.java
flint-core/src/test/scala/org/opensearch/flint/core/storage/FlintMetadataLogEntryOpenSearchConverterSuite.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintDisabledMetadataCacheWriter.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCache.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCacheWriter.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCacheWriterBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriter.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/util/IntervalSchedulerParser.java
flint-spark-integration/src/test/java/org/opensearch/flint/core/scheduler/util/IntervalSchedulerParserTest.java
flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/ApplyFlintSparkCoveringIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCacheSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/core/FlintMetadataLogITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/core/FlintTransactionITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkTransactionITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriterITSuite.scala

Manually backport #805 
* #746 

[Backport 0.5-nexus] Write metadata cache data to mappings _meta with refresh time update (#805)

---

.github/CODEOWNERS
MAINTAINERS.md

Backport #807 to update CODEOWNERS

[0.5-nexus] Update CODEOWNERS

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/FlintSparkJobExternalSchedulingService.scala

- Add external scheduler metrics
- externalScheduler.{action}.count
Tested in my dev environment:
n/a

Add external scheduler metrics

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/README.md
docs/ppl-lang/ppl-flatten-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFlattenITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/AbstractNodeVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Flatten.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/FlattenGenerator.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFlattenCommandTranslatorTestSuite.scala

The `flatten` command is introduced
https://github.com/opensearch-project/opensearch-spark/issues/669

PPl `flatten` command

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkValidationHelper.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCache.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexFactorySuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCacheSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedViewSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriterITSuite.scala

Extract source table names from mv query and add to `_meta.properties.sourceTables`
This is actually already introduced in #297, but we used it only for validation and didn't store the table names
```
CREATE MATERIALIZED VIEW myglue_test.default.mv_test_source_tables
AS SELECT status FROM myglue_test.default.http_logs
WITH (
auto_refresh = true,
checkpoint_location = 's3://test/'
)
GET flint_myglue_test_default_mv_test_source_tables/_mappings
{
"flint_myglue_test_default_mv_test_source_tables": {
"mappings": {
"_meta": {
"latestId": "ZmxpbnRfbXlnbHVlX3Rlc3RfZGVmYXVsdF9tdl90ZXN0X3NvdXJjZV90YWJsZXM=",
"kind": "mv",
"indexedColumns": [
{
"columnType": "int",
"columnName": "status"
}
],
"name": "myglue_test.default.mv_test_source_tables",
"options": {
"auto_refresh": "true", …
```

Extract source table names from mv query

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/AsyncQuerySchedulerBuilder.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/scheduler/OpenSearchAsyncQueryScheduler.java
flint-spark-integration/src/test/java/org/opensearch/flint/core/scheduler/AsyncQuerySchedulerBuilderTest.java
flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala

Failback to internal scheduler when index creation failed. This could happen during the feature deployment where the backend role is not updated for the correspond data source

Fallback to internal scheduler when index creation failed

---

docs/ppl-lang/PPL-Example-Commands.md
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParseCidrmatchTestSuite.scala

In `cidrmatch` ppl command the logical plan tests are missing

`cidrmatch` ppl command add logical tests and docs

---

docs/ppl-lang/functions/ppl-json.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLJsonFunctionITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTransformer.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJsonFunctionsTranslatorTestSuite.scala

This is a followup of PR https://github.com/opensearch-project/opensearch-spark/pull/780
1. Refactor `JSON`: Currently the `JSON` can evaluate STRING/JSON_ARRAY/JSON_OBJECT. It brings many confusions and bugs. It because in Splunk or OpenSearch, the data could be stored as JSON object, `JSON` function evaluates JSON object and return its value or null if invalid. But in Spark, there is no JSON object, but it contains STRING, StructType and ArrayType. So to evaluate a json string, `JSON` function should accept STRING type only.
2. Add `ARRAY_LENGHT`: for the same reason, the original `JSON_ARRAY_LENGHT` accepts both STRINGand JSON_ARRAY(ArrayType). We separate `JSON_ARRAY_LENGHT` to `JSON_ARRAY_LENGHT` and `ARRAY_LENGHT`. The `JSON_ARRAY_LENGHT` only accepts STRING type, `ARRAY_LENGHT` …

[followup] Refactor JSON function and add TO_JSON_STRING, ARRAY_LENGHT functions

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-join-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLJoinITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/DescribeRelation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Join.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Relation.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/SubqueryAlias.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala

Imaging a case as following: Assume table1, table2, and table3 all contain a column `id`.
```sql
select
*
from
table1 t1,
table2 t2,
table3 t3
where
t1.id = t2.id
and t1.id = t3.id
```
To rewrite above SQL query to PPL query, we will get
```sql
source = table1
| join left = t1 right = t2 ON t1.id = t2.id table2
| join left = l1 right = t3 ON t1.id = t3.id table3 // <------ issue here! 
```
The PPL query throws an exception with message:
> `t1`.`id` cannot be resolved, Did you mean one of the following? [`l1`.`id`, `l1`.`id`, `t3`.`id`].
It because the **required left side alias** `l1` overrides the table alias `t1` and `t2`.
Its logical plan looks
```
'Project [*]
+- 'Filter (('t1.id = 't2.id) AND ('t1.id = 't3.id)) <------ t1.id cannot be resolved
+- 'Join Inner
:- 'SubqueryAlias l1 …
```

Join side aliases should be optional

---

integ-test/bin/SanityTest.py
integ-test/script/README.md
integ-test/script/SanityTest.py
integ-test/script/test_cases.csv

This Python script executes test queries from a CSV file using an asynchronous query API and generates comprehensive test reports.
The script produces two report types:
1. An Excel report with detailed test information for each query
2. A JSON report containing both test result overview and query-specific details
Apart from the basic feature, it also has some advanced functionality includes:
1. Concurrent query execution (note: the async query service has session limits, so use thread workers moderately despite it already supports session ID reuse)
2. Configurable query timeout with periodic status checks and automatic cancellation if timeout occurs.
3. Flexible row selection from the input CSV file, by specifying start row and end row of the input CSV file.
4. Expected status validation …

Add sanity test script

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexFactory.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCache.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriter.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedViewSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriterITSuite.scala

Using custom implementation for `FlintIndexMetadataService` exposes a bug where we incorrectly get empty `sourceTables` from `FlintMetadata`.
Depending on how the `FlintMetadata` is generated, the `metadata.properties.get("sourceTables")` could either be of type java array or scala array.
This PR fixes the bug, now considering both cases.
Also added some logs for troubleshooting in production environment.
* #746 
* #854 

Fix bug for not able to get sourceTables from metadata

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/IndexMetricHelper.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/covering/FlintSparkCoveringIndexAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/mv/FlintSparkMaterializedViewAstBuilder.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/sql/skipping/FlintSparkSkippingIndexAstBuilder.scala

- Add metrics for query types
- drop won't be emitted in current flow since it is be executed at SQL plugin side.
Metrics emitted by tests:
n/a

Add metrics for query types

---

.github/workflows/test-and-build-workflow.yml
build.sbt

- Enable HTML test report for easier debug in case of test failure
- Test output will be available in the page for failed test cases.
- The result would be uploaded as artifact and can be downloaded as ZIP file
- The report will be stored in separate folder per package
Sample Image:
n/a

Enable HTML test report

---

DEVELOPER_GUIDE.md
docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-trendline-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLTrendlineITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Trendline.java
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/TrendlineCatalystUtils.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTrendlineCommandTranslatorTestSuite.scala

Introduce a new variant (WMA) for existing trendline ppl command, by compositing a logical plan similar to the following with function `nth_value( )` to calculate the WMA value by perform event look behind. 
```
-- +- 'Project ['name, 'salary, 
-- (((('nth_value('salary, 3) windowspecdefinition('age ASC NULLS FIRST, specifiedwindowframe(RowFrame, -2, currentrow$())) * 3) + 
-- ('nth_value('salary, 2) windowspecdefinition('age ASC NULLS FIRST, specifiedwindowframe(RowFrame, -2, currentrow$())) * 2)) + 
-- ('nth_value('salary, 1) windowspecdefinition('age ASC NULLS FIRST, specifiedwindowframe(RowFrame, -2, currentrow$())) * 1)) / 6) AS WMA#708]
-- +- 'UnresolvedRelation [employees], [], false
```
Some high level code changes:
- Update developer README to include selected set of Unit || …

New trendline ppl command (WMA)

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-where-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFiltersITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParenthesizedConditionTestSuite.scala

(cherry picked from commit a80aa04b9bbadfe68a3ed0ff59c3edce5251aac6)
Signed-off-by: Lantao Jin <ltjin@amazon.com>

[Backport 0.6] Support parenthesized expression in filter (#888)

---

flint-commons/src/main/scala/org/apache/spark/sql/exception/UnrecoverableException.scala
flint-commons/src/main/scala/org/opensearch/flint/common/model/InteractiveSession.scala
integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/util/ThrowableHandler.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Improve entry point exception handling by:
1. Support rethrow UnrecoverableException and record emr job failure
2. Switch general exception to throwable

Support UnrecoverableException

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/RelationUtils.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

Support CloudWatch table pattern `` `_CWLBasic` ``.`` `default` ``.`` `startTime:123endTime:123` ``.`` `logGroup` `` temporarily.
The correct solution should be change `` `_CWLBasic` ``.`` `default` ``.`` `startTime:123endTime:123` ``.`` `logGroup` ``  to `` `_CWLBasic` ``.`` `default` ``.`` `startTime:123endTime:123.logGroup` `` from user side.
Resolves https://github.com/opensearch-project/opensearch-spark/issues/912

Temporarily support 4+ parts table identifier

---

ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4

Due to the need to expose the latest P1 commands list of ppl antlr grammar - this PR includes the last missing `geoip` command.
It is added to the antlr files **without any other tests or functionality** for the single purpose of reflecting a complete set of grammar vocabulary parsing syntax.
#910

update `expand` antlr command

---

integ-test/script/README.md
integ-test/script/SanityTest.py

Some minor update:
1. Add `openpyxl` as the prerequisite package in README
2. Put response json in error message so it can show in the final report
3. Print test status for each test query in the log, then we can quick check status in process.

Sanity test script enhancement and doc update

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala

Temp fix for table name more than 3 parts. The describe command doesn't impact.

Temp fix for table name more than 3 parts

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkUpdateIndexITSuite.scala

Support alter from manual to auto without specifying scheduler mode. In detail:
Step 1:
Create a manual refresh index (full or incremental)
Step 2:
Alter it by set auto_refreh=true, by default it will switch to auto refresh mode and use external scheduler when `spark.flint.job.externalScheduler.enabled = true` 

Support alter from manual to auto without specifying scheduler mode

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/ppl-flatten-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFlattenITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ast/tree/Flatten.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanFlattenCommandTranslatorTestSuite.scala

Support flatten with alias. e.g.
```
source=table | flatten coor as (altitude, latitude, longitude)
source=table | flatten struct as subfield 
```
Resolve #911 
We can use alias to avoid duplicate column name in the final result.

Support flatten with alias

---

integ-test/src/integration/scala/org/apache/spark/sql/FlintJobITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala

Fix the bug where `statement.error` is not recorded after introducing `ThrowableHandler`

[Bugfix]Record statement execution error

---

flint-core/src/main/java/org/opensearch/flint/core/IRestHighLevelClient.java
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala

Rethrow exception in writeData() so that this can be recorded at top level
```
try {
dataToWrite.foreach(df => writeDataFrameToOpensearch(df, resultIndex, osClient))
} catch {
case t: Throwable =>
throwableHandler.recordThrowable(
s"Failed to write to result index. originalError='${throwableHandler.error}'",
t)
}
```

Rethrow exception in writeData()

---

build.sbt
flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala

Enable parallel integration.
Based on the metrics collected:
```
total time cost: 1h09m, test suites: 125, test cases: 1674
Cost Range: 0 min - 1 min: 109 test suites, total cost 476 sec
Cost Range: 1 min - 2 min: 5 test suites, total cost 410 sec
Cost Range: 2 min - 3 min: 3 test suites, total cost 469 sec
Cost Range: 3 min - 4 min: 7 test suites, total cost 1482 sec
Cost Range: 6 min - 7 min: 1 test suites, total cost 407 sec
```
The time cost of each suite is somehow faired. Most of test suites cost less than 1min and maximum cost is no more than 7 mins.
To reduce test execution time, we should increase parallelism, especially since we don't have any long-running test suites and all tests currently run sequentially.
**TODO**: There is another thought to reduce the average testing time …

Enable parallelExecution for integration test suites

---

docs/ppl-lang/ppl-fillnull-command.md

The example in ppl-fillnull-command.md is outdated and mismatch with our current syntax.  Update the examples with correct syntax. 

Fix ppl-fillnull-command.md

---

docs/index.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergMaterializedViewITSuite.scala

Adds support for serializing Spark's DecimalType in FlintDataType
_List any issues this PR will resolve, e.g. Resolves [...]._

Add support for serializing Spark's DecimalType

---

docs/load_geoip_data.scala
docs/opensearch-geoip.md

* Splits subnets as necessary to remove any overlap
* Is a Scala script to run in Spark CLI
* Can optionally import the data into a Spark table
* Adds 3 extra columns that will be used to find the subnet for an IP address
N/A

Add a script for importing GeoIP data

---

docs/index.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala

* Add support for serializing DecimalType in FlintDataType
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
* Fix checkstyle
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
* Add documentation on the new serialization behavior
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
* Fix integ test
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
* Actually fix integ tests
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
* Move the decimal and map IT to the base suite instead of the iceberg suite
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
---------
Signed-off-by: Chase Engelbrecht <engechas@amazon.com>
(cherry picked from commit 0943f1fbe893349688aaa84c1d1fcab69156d264)
_List any issues this PR will resolve, e.g. …

Add support for serializing Spark's DecimalType (#947)

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLFillnullITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java

Fix ambiguous exception when type mismatch in fillnull command
Resolves https://github.com/opensearch-project/opensearch-spark/issues/959

[BugFix] Fix ambiguous exception when type mismatch in fillnull command

---

ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java

Update grammar for FILLNULL to match the grammar in the PR for the SQL project
https://github.com/opensearch-project/sql/pull/3075

Updated grammar for FILLNULL to match grammar in SQL project

---

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/core/FlintOpenSearchClientSuite.scala

Add a new spark config `spark.datasource.flint.request.completionDelayMillis` to set a wait time after OpenSearch index creation is complete.
It's set to 2000 if using aoss service by default, otherwise it's 0.
* #950 
Create index with default config
<pre>
<b>24/11/26 23:49:04</b> INFO FlintOpenSearchClient: Creating Flint index flint_myglue_test_default_no_wait_time with metadata FlintMetadata(...)
24/11/26 23:49:04 INFO FlintOpenSearchClient: Creating Flint index flint_myglue_test_default_no_wait_time
24/11/26 23:49:04 INFO RetryableHttpAsyncClient: Building retryable http async client with options: FlintRetryOptions{maxRetries=3, retryableStatusCodes=429,502, retryableExceptionClassNames=Optional.empty}
24/11/26 23:49:04 INFO HttpStatusCodeResultPredicate: Checking if status code is …

Wait after create index complete

---

.github/workflows/test-and-build-workflow.yml

sbt is missing in the latest ubuntu runner release. CI failed with message:
```
Run sbt scalafmtCheckAll
/home/runner/work/_temp/1f7874ac-2254-462e-8dda-84ebc8c5e9ba.sh: line 1: sbt: command not found
Error: Process completed with exit code 127.
```
Add setup-sbt action in workflow.
Resolves https://github.com/opensearch-project/opensearch-spark/issues/977

Add setup-sbt in build workflow

---

ppl-spark-integration/src/main/java/org/opensearch/sql/ast/expression/Alias.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java

Refactor the Alias node to avoid ambiguity. See https://github.com/opensearch-project/opensearch-spark/issues/974 for details.
Resolves https://github.com/opensearch-project/opensearch-spark/issues/974

Refactor the `Alias` node to avoid ambiguity

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCache.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriter.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCacheSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriterITSuite.scala

For MV index, add a query string field into metadata cache.
In addition, preserves content in index mapping when updating the cache.
Before: `FlintOpenSearchMetadataCacheWriter` tries to serialize the `FlintMetadata` by itself, ignoring what's currently inside index mapping.
After: No longer tries to serialize `FlintMetadata` into the json string used for update index mapping. Instead, read the current index mapping, and add the required cache fields into it.
* #987 
* #931
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/sql/blob/main/CONTRIBUTING.md#developer-certificate- …

Add sourceQuery in metadata cache

---

README.md
docker/integ-test/.env
docker/integ-test/docker-compose.yml
docker/integ-test/log4j2.properties
docker/integ-test/prepare_scala_queries.py
docker/integ-test/queries.scala
docker/integ-test/spark-defaults.conf
docker/integ-test/spark-master-entrypoint.sh
integ-test/script/README.md
integ-test/script/SanityTest.py
integ-test/script/data/customer.mapping.json
integ-test/script/data/http_logs.json
integ-test/script/data/http_logs.mapping.json
integ-test/script/data/lineitem.mapping.json
integ-test/script/data/nation.mapping.json
integ-test/script/data/nested.json
integ-test/script/data/nested.mapping.json
integ-test/script/data/orders.mapping.json
integ-test/script/data/part.mapping.json
integ-test/script/data/partsupp.mapping.json
integ-test/script/data/people.json
integ-test/script/data/people.mapping.json
integ-test/script/data/region.mapping.json
integ-test/script/data/supplier.mapping.json
integ-test/script/data/work_info.json
integ-test/script/data/work_info.mapping.json
integ-test/script/test_cases.csv

Created a cluster that can later be used for integration tests. It contains a `docker-compose.yml` file that can be used to start the whole cluster.
Cluster contains:
* Spark master
* Spark worker
* OpenSearch server
* OpenSearch dashboards
* Minio server
Currently the Minio server is unused.
Spark nodes are configured to include the Flint and PPL extensions as well as to be able to query the OpenSearch server.
The OpenSearch dashboards are configured to connect to the OpenSearch server.
https://github.com/opensearch-project/opensearch-spark/issues/601 …

Created docker files for an integ test cluster (#601)

---

docs/index.md
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkIndexOptions.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndex.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedView.scala
flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexOptionsSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/FlintSparkIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/covering/FlintSparkCoveringIndexSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/mv/FlintSparkMaterializedViewSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkCoveringIndexSqlITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala

This PR enhances the Covering Index (CV) and Materialized View (MV) write operations by introducing deterministic ID generation. Deterministic IDs uniquely identify each document in a CV/MV based on its data, enabling idempotency. This ensures consistent results during retries or restarts of index refreshes. By eliminating duplicates, this approach maintains data integrity and operational consistency, even in failure scenarios.
The ID generation logic follows the precedence below:
1. **User-Provided ID Expression**
- Enables users to define custom ID generation logic based on specific columns or expressions.
- If empty, no ID column is generated, which is useful for testing or disabling the feature.
2. ~**Aggregated MV**~
- ~If MV queries involves aggregation, IDs are generated using …

Enhance CV and MV idempotency via deterministic ID generation

---

.github/workflows/test-and-build-workflow.yml

CI is failing for
> This request has been automatically failed because it uses a deprecated version of `actions/upload-artifact: v3`. Learn more: https://github.blog/changelog/2024-04-16-deprecation-notice-v3-of-the-artifact-actions/

Update to upload-artifact@v4

---

README.md
build.sbt
docs/index.md
docs/ppl-lang/PPL-on-Spark.md
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

Bumped Flint version to 0.6.1. Ref: https://github.com/opensearch-project/opensearch-spark/pull/360
```
clingzhi@88665a1d4119 opensearch-spark % find . -name "*-0.6.0-SNAPSHOT.jar"
clingzhi@88665a1d4119 opensearch-spark % find . -name "*-0.6.1-SNAPSHOT.jar"
./integ-test/target/scala-2.12/integ-test-assembly-0.6.1-SNAPSHOT.jar
./spark-sql-application/target/scala-2.12/sql-job-assembly-0.6.1-SNAPSHOT.jar
./flint-spark-integration/target/scala-2.12/flint-spark-integration-assembly-0.6.1-SNAPSHOT.jar
./ppl-spark-integration/target/scala-2.12/ppl-spark-integration-assembly-0.6.1-SNAPSHOT.jar
./flint-commons/target/scala-2.12/flint-commons-assembly-0.6.1-SNAPSHOT.jar
```
For more …

Bump Flint version to 0.6.1

---

build.sbt

* Unshaded auth-crt library to address the `UnsatisfiedLinkError`. This change is necessary due to a known issue where a temporary library copy is created for loading, and the `CRT_LIB_NAME` constant cannot be altered.
https://github.com/awslabs/aws-crt-java/issues/166
```
java.lang.NoClassDefFoundError: Could not initialize class shaded.flint.software.amazon.awssdk.crt.auth.signing.AwsSigningConfig
at shaded.flint.software.amazon.awssdk.authcrt.signer.internal.SigningConfigProvider.createStringToSignConfig(SigningConfigProvider.java:111) ~[opensearch-spark-standalone_2.12-latest.jar:0.6.0-SNAPSHOT]
at shaded.flint.software.amazon.awssdk.authcrt.signer.internal.SigningConfigProvider.createDefaultRequestConfig(SigningConfigProvider.java:91) …
```

Unshade auth-crt due to known issue

---

.github/workflows/stalled.yml

Copies the stalled PR workflow from OS core: https://github.com/opensearch-project/OpenSearch/blob/main/.github/workflows/stalled.yml
N/A

Add stalled PRs workflow

---

docs/ppl-lang/PPL-Example-Commands.md
docs/ppl-lang/functions/ppl-datetime.md
docs/ppl-lang/ppl-where-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltInDateTimeFunctionITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTransformer.java

Signed-off-by: currantw <taylor.curran@improving.com>
Implements `earliest` and `latest` relative date time functions in PPL.
Resolves #957 
- `PPL-Example-Commands.md`
- `ppl-datetime.md`
- `ppl-where-command.md`
- `TimeUtilsTest`
- `SerializableTimeUdfTest`
- `FlintSparkPPLBuiltInDateTimeFunctionITSuite`

#957 Implement `earliest` and `latest` functions

---

docs/ppl-lang/functions/ppl-datetime.md
integ-test/script/data/relative_datetime.json
integ-test/script/data/relative_datetime.mapping.json
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltInDateTimeFunctionITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4

Add support for using `earliest` and `latest` relative time functions with the `where` command.
Resolved #1020.

#1020: `earliest`/`latest` not supported with `where` command

---

docs/opensearch-table.md
integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableQueryITSuite.scala

1. Add Join and Lookup IT on OpenSearch Table.
2. Add Join example in OpenSearch Table doc 
n/a

Add Join and Lookup IT on OpenSearch Table

---

docs/opensearch-table.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableITSuite.scala
integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableQueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala

This PR introduces support for alias fields in `FlintDataType`, allowing fields to be referenced by alternative names. The change enables schema parsing and JSON processing to recognize alias fields and map them to their corresponding primary fields.
1. **FlintDataType.scala**
- Updated `deserializeJValue` to identify and process alias fields.
- Modified `deserializeField` to support alias metadata assignment.
2. **FlintJacksonParser.scala**
- Implemented `fieldMapping` to associate JSON keys with schema field indices, allowing alias fields to be correctly resolved during parsing.
- Updated JSON parsing logic to handle multiple schema fields mapped to a single JSON key.
3. **Add OpenSearch Table datatype in docs**
- https://github.com/penghuo/penghuo-opensearch-spark/blob/dataTypeAlias/doc …

Support OpenSearch alias field type

---

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/http/FlintRetryOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/http/handler/HttpStatusCodeResultPredicate.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/BulkRequestRateLimiterImpl.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/OpenSearchBulkWrapper.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/RequestRateMeter.java
flint-core/src/test/java/org/opensearch/flint/core/storage/RequestRateMeterTest.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala

- Based on testing adaptive rate limit implementation with data, I identified following issues:
- Rate limit was increase even when the current limit is not fully utilized, and this lead to too high rate limit and limit decrease took long time to become effective.
- As the rate limit is adjusted when a request finished, adjustment frequency depends on the current request rate. (means rate limit is increased slowly when rate limit is low, and quickly when rate limit is high)
- This PR address the first issue. (Second issue is not critical as far as we don't set minimum rate to lower value. current value is 5000)
- BulkRequestRateMeter collect data points for current rate using recent 3 seconds window, and calculate the estimated current rate. If the current rate is lower than 80% of rate …

Stabilize adaptive rate limit by considering current rate

---

docs/ppl-lang/ppl-lookup-command.md
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLLookupITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/LookupTransformer.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/RelationUtils.java
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintPPLSparkExtensions.scala
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParser.scala
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/PPLSparkUtils.scala

**issue-1:**
The current behaviour of [inputField](https://github.com/opensearch-project/opensearch-spark/blob/main/docs/ppl-lang/ppl-lookup-command.md) is "If you don't specify any `<inputField>`, **all fields of `<lookupIndex>`** where matched values are applied to result output." 
The correct behaviour should be "If you don't specify any `<inputField>`, **all fields of `<lookupIndex>` that are not the mapping fields** where matched values are applied to result output." 
**issue-2:**
A known bug. The existing IT "test LOOKUP lookupTable name REPLACE occupation" provided a workaround. The PR fixed the issue and provide a new IT "test LOOKUP lookupTable name REPLACE occupation - 2"
Resolves https://github.com/opensearch-project/opensearch-spark/issues/1026
By submitting this pull request, …

[BUG] Fix the PPL Lookup command behavior when inputField is missing and REPLACE with existing fields

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/MetricConstants.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
integ-test/src/integration/scala/org/apache/spark/sql/FlintJobITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJob.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/util/WarmpoolTest.scala

This PR introduces support for FlintJob to handle all types of queries — interactive, streaming, and batch — with all data sources in warmpool mode. Additionally, FlintJob will also support non-warmpool mode for streaming and batch queries, configurable via a Spark configuration setting.
FlintJob invokes `Warmpool.scala`, which in turn calls the client to continuously fetch queries for execution. The client sets various Spark configurations, such as the datasource, resultIndex, and other parameters. It also controls when to terminate the loop and stop the job. When a valid query is received, the JobOperator flow is triggered to execute the query and write the results accordingly.
**Changes:**
- Introduces a new file, Warmpool.scala, which repeatedly calls `getNextStatement()` in a loop.
- …

Implement FlintJob to handle all query types in warmpool mode

---

.github/workflows/end-to-end-test-workflow.yml
.github/workflows/test-and-build-workflow.yml
e2e-test/src/test/scala/org/opensearch/spark/e2e/EndToEndITSuite.scala

Move the end-to-end tests to a separate workflow. Also lowered the timeout for starting the docker cluster to 20 minutes.
None

Move end-to-end tests to a separate workflow

---

e2e-test/src/test/resources/spark/queries/ppl/query_177.results
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/storage/FlintQueryCompiler.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/storage/FlintQueryCompilerSuite.scala

1. Fix bug in QueryCompiler to correct handle `NOT "textField" = "literalString"`. It should not be push down to DSL.
2. Remove unexpected result from Query_177.results.
[Fix Query_177 failure.](https://github.com/opensearch-project/opensearch-spark/issues/1056)

Fix CI failed related to query_177

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBasicITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLInSubqueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLScalarSubqueryITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystPlanContext.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/LookupTransformer.java

Issue described in https://github.com/opensearch-project/opensearch-spark/issues/1058.
Root cause is missing reset expression stack before resolving project list.
Resolves https://github.com/opensearch-project/opensearch-spark/issues/1058

Clean expression stack before resolving project list

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLGeoipITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLJsonFunctionITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/SerializableUdf.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystExpressionVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTransformer.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/GeoIpCatalystLogicalPlanTranslator.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanGeoipFunctionTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJsonFunctionsTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanParseCidrmatchTestSuite.scala

Unify all PPL functions in BuiltinFunctionName. This PR includes change:
- Add all PPL functions we have currently in `BuiltinFunctionName`, that place should be the single of truth to maintain all PPL built-in functions.
- For code robust improvement, `SerializableUdf::visit` change to use function enumerator as its switch key instead of string.
- Add `PPL_TO_SPARK_UDF_MAPPING` in `BuiltinFunctionTransformer` to do transformation of PPL built-in function to Spark UDF we implemented in this project.
Resolves: https://github.com/opensearch-project/opensearch-spark/issues/1051
For more information on following Developer Certificate of Origin and signing off your commits, please …

[Enhancement] Unify all PPL functions in BuiltinFunctionName

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLRenameITSuite.scala
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanBasicQueriesTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanRenameTranslatorTestSuite.scala
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanTrendlineCommandTranslatorTestSuite.scala

Fix customer ticket V1653686949, details in #1063 
Resolves #1063 

Alias could be wrapped with backticks in RENAME and other commands

---

docs/ppl-lang/ppl-dedup-command.md

Remove [unsupported dedup consecutive paramaters](https://github.com/opensearch-project/opensearch-spark/blob/main/integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLDedupeITSuite.scala#L176) from doc. 
_List any issues this PR will resolve, e.g. Resolves [...]._

Remove unsupported dedup consecutive paramaters from doc

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLJoinITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/CatalystQueryPlanVisitor.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstBuilder.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanJoinTranslatorTestSuite.scala

Multiple tables as join right without subsearch is not allowed:
- `JOIN on id = uid table1,table2` is not allowed
- `JOIN on id = uid table1,table2 as t2` is not allowed
- `JOIN on id = uid [ source = table1,table2 ]` is allowed
- `JOIN on id = uid [ source = table1,table2 ] as t2` is allowed
Resolves #1073 

Multiple tables as join right without subsearch is not allowed

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLBuiltInDateTimeFunctionITSuite.scala
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/BuiltinFunctionTransformer.java

Support QUARTER interval in date_add/date_sub
Resolves https://github.com/opensearch-project/opensearch-spark/issues/1098

Support QUARTER interval in date_add/date_sub

---

docs/opensearch-table.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintMetadataExtensions.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableQueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala

- Support half_float data type in OpenSearch
- half_float is mapped to float in Spark
https://github.com/opensearch-project/opensearch-spark/issues/1048

Support half_float data type in OpenSearch

---

flint-core/src/main/scala/org/opensearch/flint/core/http/handler/HttpStatusCodeResultPredicate.java

I noticed a lot of log lines in the EMR logs are repeating things like
```
25/04/09 22:03:26 INFO HttpStatusCodeResultPredicate: Checking if status code is retryable: 200
25/04/09 22:03:26 INFO HttpStatusCodeResultPredicate: Status code 200 check result: false
25/04/09 22:03:27 INFO HttpStatusCodeResultPredicate: Checking if status code is retryable: 200
25/04/09 22:03:27 INFO HttpStatusCodeResultPredicate: Status code 200 check result: false
```
Duplicates of these lines make up ~17% of the log.
This PR cuts that number in half. The lines now look like:
```
25/04/09 22:25:09 INFO HttpStatusCodeResultPredicate: 200 is not retryable
25/04/09 22:25:10 INFO HttpStatusCodeResultPredicate: 200 is not retryable
```
We should log 2xx statuses as `debug` instead of `info`, but I'm erring to the …

tweak: Reduce status retry logging

---

spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

**…results**
This change ensures correct DataFrame formatting for non-streaming/batch queries by calling the processing step before writing results. Following the same standard here as pre #979 FlintREPL which was responsible for handling these queries. 
NA

Call processDataframe before writeDataFrame for non Streaming Or Batch queries

---

build.sbt
docs/opensearch-table.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/IPAddress.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/IPAddressUDT.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/IPFunctions.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/udt/IPAddressTest.scala
integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableQueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala

- Support OpenSearch ip field type
- This PR implements ip field to be stored as UDT.
- It is using UDT to prioritize the type compatibility with OpenSearch.
- Pushdown logic will be implemented separately.
- Original PR (using string type): https://github.com/opensearch-project/opensearch-spark/pull/1044
https://github.com/opensearch-project/opensearch-spark/issues/1034

Support OpenSearch ip field type (UDT)

---

build.sbt
docs/opensearch-table.md
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/datatype/FlintDataType.scala
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/json/FlintJacksonParser.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSparkExtensions.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/GeoPoint.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/GeoPointConverter.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/udt/GeoPointUDT.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/datatype/FlintDataTypeSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/udt/GeoPointConverterSuite.scala
integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchTableQueryITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/OpenSearchSuite.scala

- Add geo_point OpenSearch type support
- geo_point is implemented as UDT to prioritize type compatibility with OpenSearch
https://github.com/opensearch-project/opensearch-spark/issues/1047

Add geo_point OpenSearch type support

---

integ-test/src/integration/scala/org/apache/spark/sql/FlintREPLITSuite.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/FlintREPLTest.scala

Pass execptionType in error message in case of queryFailure
* We pass exception type to error message so upstream services can use the exception type from the error message to parse

Pass execptionType in error message

---

DEVELOPER_GUIDE.md
integ-test/src/aws-integration/scala/org/opensearch/flint/spark/aws/AWSEmrServerlessAccessTestSuite.scala

`AWSEmrServerlessAccessTestSuite` wouldn't run due to misconfigured spark properties in submitted spark job.
We don't test this in CI, so new requirements for spark properties in the future might still break this suite unnoticed.

Fix AWS EMR-S integration test

---

DEVELOPER_GUIDE.md

Fixes typo in #1125 
Will close existing auto backport for #1125 and instead manual backport both these PRs

Fix doc typo for aws integration test

---

flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/metrics/MetricsSparkListener.scala
flint-core/src/test/scala/org/opensearch/flint/core/metrics/MetricsSparkListenerTest.scala

- Add account dimension to bytesRead metric, so that we can track how much data was analyzed by each customer. 
- We already have accountId in environment variable `FLINT_CLUSTER_NAME`, so this PR adds the accountId to metric dimension by utilizing DimensionedName ([ref](https://github.com/opensearch-project/opensearch-spark/blob/09aba20a7f3121d045f979c5cbcd32bff508a317/flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionedCloudWatchReporter.java#L475))
- bytesRead is reported from [MetricsSparkListener](https://github.com/opensearch-project/opensearch-spark/blob/main/flint-core/src/main/scala/org/opensearch/flint/core/metrics/MetricsSparkListener.scala).
- [] Add `backport 0.x` label if it is a stable change which won't break existing feature
By submitting this …

Add account dimension to bytesRead metrics

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/test/scala/org/apache/spark/FlintSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriterITSuite.scala

Enable config of meta data cache
_List any issues this PR will resolve, e.g. Resolves [...]._

[Vended Dashboards] Enable config of meta data cache by default

---

integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewIntegrationCloudTrailITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewIntegrationVPCITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewIntegrationWAFITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewIntegrationsITSuite.scala

Changes are only in ```FlintSparkMaterializedViewIntegrationsITSuite.scala```
Modified integration test for Materialized View.
Originally the integration test uses data fetched from ```_source```, with the implementation of the feature of disabling _source it's no longer sufficient for testing.
This PR rewrote the integration test to make it fetch data from ```openSearchClient``` instead of ```_source```
Implemented testing for 
```VPC flow``` with unfiltered time series chart and pie chart.
```CloudTrail``` with unfiltered time series chart and pie chart.
```WAF``` with unfiltered time series chart and pie chart.

Rewrote Integration Test for VPC, CloudTrail and WAF to test without fetching data from _source

---

docker/integ-test/queries.scala
e2e-test/src/test/resources/opensearch/queries/ppl/query_123.ppl
e2e-test/src/test/resources/opensearch/queries/ppl/query_124.ppl
e2e-test/src/test/resources/spark/queries/ppl/query_123.ppl
e2e-test/src/test/resources/spark/queries/ppl/query_124.ppl
integ-test/script/test_cases.csv
integ-test/src/integration/resources/opensearch/dashboards_sample_data_flights_tests.json
integ-test/src/integration/scala/org/apache/spark/opensearch/table/OpenSearchDashboardITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLLookupITSuite.scala
ppl-spark-integration/src/main/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLParser.scala

Fields identifier in PPL should be case sensitive which is aligning with OpenSearch PPL. Ref https://github.com/opensearch-project/opensearch-spark/issues/1146
Resolves https://github.com/opensearch-project/opensearch-spark/issues/1146

Fields identifier in PPL should be case sensitive

---

flint-spark-integration/src/main/scala/org/opensearch/flint/spark/FlintSpark.scala
flint-spark-integration/src/main/scala/org/opensearch/flint/spark/metadatacache/FlintMetadataCache.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/metadatacache/FlintOpenSearchMetadataCacheWriterITSuite.scala

Useful for detecting the current status of data sources from OSD, particularly for Dashboards to know if an index is currently refreshing or not.
There's a quirk with the `creating` state not being switched off until the next refresh picks it up. I think it's technically a bug, but I think we can/should leave it as-is since it's more directly useful to the front-end that an index is newly created but not yet started refreshing: I added a comment and wrote tests around this. Alternatively, I could do some refactoring to make it work right, probably adding some cache-flush layer directly in `metadata.copy` that makes it update by default.
[Example of how this is used on the front-end](https://github.com/Swiddis/OpenSearch-Dashboards/compare/18d96875a4503773a6691a22947ed3fb6cbfd7f5...ad579c3c …

Add index state to metadata cache

---

.github/publish-utils.sh
.github/workflows/snapshot-publish.yml

Changes Overview
This PR enhances the snapshot publishing workflow by implementing a commit-to-version mapping mechanism with detailed artifact information.
Key Improvements
Commit-Version Mapping File
`commit-history.json`
Created mapping structure with detailed artifact version information:
```
{
"mappings": [
{
"commit_id": "abc123...",
"version": "1.0.0-SNAPSHOT",
"timestamp": "2023-06-15T14:32:17Z",
"artifacts": {
"opensearch-spark-standalone_2.12": "1.0.0-20230615.143217-1",
"opensearch-spark-ppl_2.12": "1.0.0-20230615.143217-1",
"opensearch-spark-sql-application_2.12": "1.0.0-20230615.143217-1"
}
}
]
}
```
example mapping:
https://aws.oss.sonatype.org/content/repositories/snapshots/org/opensearch/commit-history.json
Implemented intelligent merging of new data with existing records …

Add Commit-Based Artifact Download Support

---

flint-commons/src/main/scala/org/opensearch/flint/common/model/FlintStatement.scala
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

Previously, the JobOperator was not updating the FlintStatement status before passing it to the QueryResultWriter, causing it to receive statements with incorrect/stale status information. This pr Updates the statement based on query execution result.
_List any issues this PR will resolve, e.g. Resolves [...]._

set correct Flint Statement State after query execution

---

.github/publish-utils.sh
.github/workflows/snapshot-publish.yml

Update snapshot uploading
I changed the path to fetch the publish-snapshot.sh(https://github.com/opensearch-project/opensearch-build/blob/main/publish/publish-snapshot.sh) from opensearch-build-libraries to opensearch-build since this file no longer exists in opensearch-build-libraries

fix snapshot uploading

---

.github/publish-utils.sh
.github/workflows/link-checker.yml
.github/workflows/snapshot-publish.yml
.lychee.excludes
docs/index.md

Switches from the deprecated AWS OSS Sonatype server to Maven Central.
Based on https://github.com/opensearch-project/opensearch-java/pull/1634
https://github.com/opensearch-project/opensearch-build/issues/5548

Switch from AWS OSS sonatype to Maven Central

---

.pre-commit-config.yaml
DEVELOPER_GUIDE.md

Has this ever happened to you?
With the power of [modern technology](https://pre-commit.com/), it no longer has to!
---
Has no effect if you don't want to opt-in, but speaking for myself, I've forgotten to scalafmtApply for the last time.
If you do opt-in, with the `--client` hotfix, checking styling and warnings will automatically happen on every commit, and it goes ~20x faster than if you do it yourself.
N/A

Add precommit for Scala linting

---

.github/publish-utils.sh
.github/workflows/snapshot-publish.yml
project/GrammarDownload.scala

Disable commit-history file creation in snapshot publishing workflow to comply with Maven Central repository restrictions.
Maven Central Sonatype repository enforces strict rules about the types of files that can be uploaded to their snapshot repository. 
Our custom commit-history-*.json files are being rejected by Maven Central as they are non-standard artifacts
What still works
- Snapshot artifacts are published normally
- Commit IDs are still injected into maven-metadata.xml files for traceability
- All standard Maven repository operations continue to function
What is disabled
- Creation of commit-history JSON files in the artifact structure
- Upload of commit mapping files to the repository
Tested on #1265

Disbale commit-history file uploading
