opensearch-project/opensearch-spark

docs/index.md
flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java
flint-core/src/main/scala/org/opensearch/flint/core/storage/FlintOpenSearchClient.java
flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala

1. post new PR, in case previous PR https://github.com/opensearch-project/opensearch-spark/pull/14 closed after public the repo.
2. add integration doc. https://github.com/penghuo/penghuo-opensearch-spark/blob/assumeRole/docs/index.md#aws-emr-serverless-spark-integration---using-assume-role

Support assume role

---

.github/workflows/snapshot-publish.yml
build.sbt
spark-sql-application/README.md
spark-sql-application/src/main/scala/org/opensearch/sql/SQLJob.scala
spark-sql-application/src/test/scala/org/opensearch/sql/SQLJobTest.scala

- Moving https://github.com/opensearch-project/sql/issues/1722 from [sql](https://github.com/opensearch-project/sql) repo to [opensearch-spark](https://github.com/opensearch-project/opensearch-spark) repo
- Updating snapshot publish workflow to include spark-sql-application jar
Reopening https://github.com/opensearch-project/opensearch-spark/pull/13

Moving spark-sql-application

---

.github/workflows/backport.yml

Update backport plugin version to 2.2.0
n/a

Update backport plugin version to 2.2.0

---

spark-sql-application/src/main/scala/org/opensearch/sql/SQLJob.scala

Format Fix

---

README.md

Corrected Documentation for spark extensions.

Corrected Documentation

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala

hard code append the FlintPPLSparkExtensions to the spark conf creation by the FlintREPL
#108

append the FlintPPLSparkExtensions to the spark conf 

---

MAINTAINERS.md

Add a maintainer to the Maintainer's list

add a maintainer 

---

MAINTAINERS.md

Add a maintainer to the Maintainer's list

Welcome maintainer kaituo

---

.github/CODEOWNERS

Add a kaituo and lior to codeowners

add kaituo and lior to codeowner list

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/config/FlintSparkConf.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/flint/config/FlintSparkConfSuite.scala

update refresh policy to wait_for

update default refresh policy to wait_for

---

flint-core/src/main/scala/org/opensearch/flint/core/FlintOptions.java

Reduce default inactivity limit to 3 min
n/a

Reduce default inactivity limit to 3min

---

MAINTAINERS.md

Welcome new maintainer Louis Chu

Welcome new maintainer Louis Chu

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala

Remove query log from job executor.
Logging it would require sensitive info anonymized like: https://github.com/opensearch-project/sql/blob/2649200e065dff48282dce438ceb0ee5ac39054e/sql/src/main/java/org/opensearch/sql/sql/antlr/AnonymizerListener.java#L34.

Remove query log from job executor

---

flint-spark-integration/src/main/scala/org/apache/spark/sql/flint/package.scala
flint-spark-integration/src/test/scala/org/apache/spark/sql/FlintCatalogSuite.scala
flint-spark-integration/src/test/scala/org/opensearch/flint/spark/skipping/ApplyFlintSparkSkippingIndexSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkMaterializedViewSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSkippingIndexSqlITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/iceberg/FlintSparkIcebergSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/sessioncatalog/FlintSessionCatalogSuit.scala
integ-test/src/test/scala/org/opensearch/flint/spark/sessioncatalog/FlintSessionCatalogSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/sessioncatalog/FlintSparkSessionCatalogMaterializedViewITSuite.scala
integ-test/src/test/scala/org/opensearch/flint/spark/sessioncatalog/FlintSparkSessionCatalogSkippingIndexITSuite.scala

* Refactor SessionCatalog as proposed. https://github.com/opensearch-project/opensearch-spark/issues/319#issuecomment-2099630984. 
* Fix IcebergIT. https://github.com/opensearch-project/opensearch-spark/pull/342/files#diff-702962c93704dbc76b65c7c622071b3ee03476641c25308afa89f906dde8ad00. 
* Add SessionCatalog IT.
https://github.com/opensearch-project/opensearch-spark/issues/319

Refactor SessionCatalog and Fix IcebergIT

---

integ-test/src/test/scala/org/opensearch/flint/spark/FlintSparkWindowingFunctionITSuite.scala

Fix FlintSparkWindowingFunctionITSuite
https://github.com/opensearch-project/opensearch-spark/issues/331

Fix FlintSparkWindowingFunctionITSuite

---

ppl-spark-integration/README.md

* Update README to reflect available commands
n/a

Update README to reflect available commands

---

README.md

Fix outdated Readme
https://github.com/opensearch-project/opensearch-spark/issues/545

Some fixes for the README

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala

Implement stddev_samp and stddev_pop ppl stats function
https://github.com/opensearch-project/opensearch-spark/issues/483

Implement stddev_samp and stddev_pop ppl stats function

---

integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationWithSpanITSuite.scala
integ-test/src/integration/scala/org/opensearch/flint/spark/ppl/FlintSparkPPLAggregationsITSuite.scala
ppl-spark-integration/README.md
ppl-spark-integration/src/main/antlr4/OpenSearchPPLLexer.g4
ppl-spark-integration/src/main/antlr4/OpenSearchPPLParser.g4
ppl-spark-integration/src/main/java/org/opensearch/sql/expression/function/BuiltinFunctionName.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/parser/AstExpressionBuilder.java
ppl-spark-integration/src/main/java/org/opensearch/sql/ppl/utils/AggregatorTranslator.java
ppl-spark-integration/src/test/scala/org/opensearch/flint/spark/ppl/PPLLogicalPlanAggregationQueriesTranslatorTestSuite.scala

This PR implements the percentile PPL stats function
https://github.com/opensearch-project/opensearch-spark/issues/482

Add percentile PPL function

---

build.sbt
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala

Update shaded rules to address the runtime problem where SLF4J not found

update shaded rules

---

.github/pull_request_template.md

Add following check list in pull request template
```
```
https://github.com/opensearch-project/opensearch-spark/issues/793

Add check list in pull request template

---

build.sbt
spark-sql-application/src/main/scala/org/apache/spark/sql/FlintJobExecutor.scala

Apply shaded rules to prevent potential jar hell issue 

Apply shaded rules

---

spark-sql-application/src/main/scala/org/apache/spark/sql/FlintREPL.scala

- Fix build issue due to import (caused by merge conflict)
n/a

Fix build issue due to import

---

README.md
build.sbt
docs/index.md
docs/ppl-lang/PPL-on-Spark.md
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

Upgrade Flint to 0.8.0

---

DEVELOPER_GUIDE.md
integ-test/src/aws-integration/scala/org/opensearch/flint/spark/aws/AWSEmrServerlessAccessTestSuite.scala

Manual backport for 939ece71 from #1125 and 194bba02 from #1128

[Backport 0.7] Fix AWS EMR-S integration test

---

DEVELOPER_GUIDE.md
integ-test/src/aws-integration/scala/org/opensearch/flint/spark/aws/AWSEmrServerlessAccessTestSuite.scala

Manual backport for 939ece71 from #1125 and 194bba02 from #1128

[Backport 0.x] Fix AWS EMR-S integration test

---

.github/workflows/snapshot-publish.yml
build.sbt
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

change the version on parent metadata file

change the version on parent metadata file

---

.github/workflows/snapshot-publish.yml
build.sbt
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

This PR modified workflow to fetch the last commit id during workflow and then add it to the metadata file

modified workflow and add last commit id to the metadata file

---

.github/workflows/snapshot-publish.yml
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

modified workflow and add last commit id to the metadata file
create a separate metadata file for the last commit_id

[Backport 0.7]modified workflow and add last commit id to a separate metadata file

---

.github/workflows/snapshot-publish.yml
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

modified workflow and add last commit id to the metadata file
create a separate metadata file for the last commit_id

[Backport 0.x]modified workflow and add last commit id to a separate metadata file

---

.github/workflows/snapshot-publish.yml
build.sbt
flint-commons/src/main/scala/org/opensearch/flint/common/FlintVersion.scala

Download and add the last commit_id to maven-metadata.xml, also delete old metadata.xml files

Download and add the last commit_id to maven-metadata.xml, also delete old metadata.xml files

---

.github/workflows/snapshot-publish.yml
build.sbt

upload new file to map commit_id and version

upload new file to map commit_id and version

---

.github/workflows/snapshot-publish.yml
build.sbt

update dependency flow using build.sbt, map commit_id and actual version

update dependency flow using build.sbt, map commit_id and actual version

---

.github/publish-utils.sh
.github/workflows/snapshot-publish.yml

Signed-off-by: Kai Huang <ahkcs@amazon.com>
(cherry picked from commit 1c41d679e3ef6782908ed4b05978c64e166092cf)

[Backport 0.x] Add Commit-Based Artifact Download Support (#1225)

---

spark-sql-application/src/main/scala/org/apache/spark/sql/WarmpoolJob.scala
spark-sql-application/src/test/scala/org/apache/spark/sql/util/WarmpoolTest.scala

This PR improves error handling in the Warmpool Job implementation by:
Adding proper exception handling in queryLoop
Ensuring cleanUpResources is called even when exceptions occur
Gracefully handling cleanup failures
Adding comprehensive unit tests for error scenarios
Resolves - Jobs getting stuck in "assigned" state when receiving 5xx errors from DQS services, causing:
Resource wastage (vCPUs held by idle jobs)
Warm pool under-provisioning

Handle Exception in queryLoop and cleanUpResources for Warmpool Job

---

flint-core/src/main/java/org/opensearch/flint/core/metrics/reporter/DimensionUtils.java
spark-sql-application/src/main/scala/org/apache/spark/sql/JobOperator.scala

Description
Add compute platform in Segment name
Related Issues
N/A
Check List
[ N/A] Updated documentation (docs/ppl-lang/README.md)
[ N/A] Implemented unit tests
[ N/A] Implemented tests for combination with other commands
[ N/A] New added source code should include a copyright header
[Y ] Commits are signed per the DCO using --signoff
[Y ] Add backport 0.x label if it is a stable change which won't break existing feature

Add compute platform in Segment name

---

.github/publish-utils.sh
.github/workflows/snapshot-publish.yml

Create initial mapping file first for normal workflow to fetch and trigger automatic run

create inital mapping file

---

.github/publish-utils.sh
.github/workflows/snapshot-publish.yml

Try using post for uploading files in central maven

Try using POST for uploading files

---

.github/publish-utils.sh
.github/workflows/snapshot-publish.yml

Try using POST to upload files that are non-maven artifacts

Fix snapshot upload

---

.github/publish-utils.sh

Fix syntax issue that is causing the failure for github CI workflow

fix syntax

---

.github/publish-utils.sh

Temporarily remove commit-history uploading and make sure that snapshot uploading is still successful

Remove commit-history uploading
